import React, { Component } from "react";
// import axios from "axios";
// import ReactDOM from 'react-dom';
// import CytoscapeComponent from 'react-cytoscapejs';
// import cytoscape from 'cytoscape';
import Cytoscape from 'cytoscape';
import CytoscapeComponent from 'react-cytoscapejs';
import Dagre from 'cytoscape-dagre';
// import Euler from 'cytoscape-euler';

Cytoscape.use(Dagre);
// Cytoscape.use(Euler);



class VisualizeCaseReport extends Component {

  constructor() {
    super();

    this.state = {
      caseReport: {

        "_id": {
            "$oid": "5cabedbbd2e9756366559ff8"
        },
        "messages": [],
        "source_files": [
            "ann",
            "txt"
        ],
        "modifications": [],
        "normalizations": [],
        "entities": [
            [
                "T1",
                "Age",
                [
                    [
                        33,
                        44
                    ]
                ]
            ],
            [
                "T2",
                "Sex",
                [
                    [
                        45,
                        50
                    ]
                ]
            ],
            [
                "T3",
                "Biological_structure",
                [
                    [
                        79,
                        98
                    ]
                ]
            ],
            [
                "T5",
                "History",
                [
                    [
                        154,
                        163
                    ]
                ]
            ],
            [
                "T6",
                "History",
                [
                    [
                        173,
                        192
                    ]
                ]
            ],
            [
                "T7",
                "History",
                [
                    [
                        260,
                        268
                    ]
                ]
            ],
            [
                "T13",
                "Detailed_description",
                [
                    [
                        356,
                        373
                    ]
                ]
            ],
            [
                "T22",
                "Nonbiological_location",
                [
                    [
                        732,
                        740
                    ]
                ]
            ],
            [
                "T24",
                "History",
                [
                    [
                        800,
                        806
                    ]
                ]
            ],
            [
                "T31",
                "Lab_value",
                [
                    [
                        884,
                        893
                    ]
                ]
            ],
            [
                "T32",
                "Lab_value",
                [
                    [
                        895,
                        901
                    ]
                ]
            ],
            [
                "T37",
                "Nonbiological_location",
                [
                    [
                        1040,
                        1048
                    ]
                ]
            ],
            [
                "T40",
                "Subject",
                [
                    [
                        983,
                        987
                    ]
                ]
            ],
            [
                "T42",
                "Subject",
                [
                    [
                        1092,
                        1103
                    ]
                ]
            ],
            [
                "T44",
                "Nonbiological_location",
                [
                    [
                        1156,
                        1164
                    ]
                ]
            ],
            [
                "T47",
                "Lab_value",
                [
                    [
                        1224,
                        1233
                    ]
                ]
            ],
            [
                "T48",
                "Lab_value",
                [
                    [
                        1235,
                        1243
                    ]
                ]
            ],
            [
                "T49",
                "Lab_value",
                [
                    [
                        1262,
                        1270
                    ]
                ]
            ],
            [
                "T53",
                "Detailed_description",
                [
                    [
                        1447,
                        1457
                    ]
                ]
            ],
            [
                "T59",
                "Subject",
                [
                    [
                        1665,
                        1677
                    ]
                ]
            ],
            [
                "T60",
                "Family_history",
                [
                    [
                        1684,
                        1744
                    ]
                ]
            ],
            [
                "T61",
                "Family_history",
                [
                    [
                        1803,
                        1836
                    ]
                ]
            ],
            [
                "T62",
                "Family_history",
                [
                    [
                        1746,
                        1759
                    ]
                ]
            ],
            [
                "T63",
                "Subject",
                [
                    [
                        1868,
                        1871
                    ]
                ]
            ],
            [
                "T64",
                "Family_history",
                [
                    [
                        1857,
                        1860
                    ]
                ]
            ],
            [
                "T65",
                "Family_history",
                [
                    [
                        1905,
                        1933
                    ]
                ]
            ],
            [
                "T66",
                "Subject",
                [
                    [
                        1956,
                        1962
                    ]
                ]
            ],
            [
                "T67",
                "Family_history",
                [
                    [
                        1945,
                        1948
                    ]
                ]
            ],
            [
                "T68",
                "Family_history",
                [
                    [
                        1975,
                        1990
                    ]
                ]
            ],
            [
                "T69",
                "History",
                [
                    [
                        1992,
                        2059
                    ]
                ]
            ],
            [
                "T70",
                "Subject",
                [
                    [
                        2149,
                        2173
                    ]
                ]
            ],
            [
                "T71",
                "Family_history",
                [
                    [
                        2070,
                        2141
                    ]
                ]
            ],
            [
                "T72",
                "Nonbiological_location",
                [
                    [
                        2311,
                        2336
                    ]
                ]
            ],
            [
                "T80",
                "Biological_structure",
                [
                    [
                        2629,
                        2657
                    ]
                ]
            ],
            [
                "T83",
                "Detailed_description",
                [
                    [
                        2789,
                        2794
                    ]
                ]
            ],
            [
                "T84",
                "Detailed_description",
                [
                    [
                        2827,
                        2846
                    ]
                ]
            ],
            [
                "T85",
                "Detailed_description",
                [
                    [
                        2848,
                        2895
                    ]
                ]
            ],
            [
                "T86",
                "Detailed_description",
                [
                    [
                        3011,
                        3035
                    ]
                ]
            ],
            [
                "T88",
                "Detailed_description",
                [
                    [
                        3076,
                        3090
                    ]
                ]
            ],
            [
                "T89",
                "Detailed_description",
                [
                    [
                        3092,
                        3153
                    ]
                ]
            ],
            [
                "T90",
                "Detailed_description",
                [
                    [
                        3159,
                        3170
                    ]
                ]
            ],
            [
                "T92",
                "Detailed_description",
                [
                    [
                        3204,
                        3216
                    ]
                ]
            ],
            [
                "T93",
                "Detailed_description",
                [
                    [
                        3233,
                        3250
                    ]
                ]
            ],
            [
                "T94",
                "Detailed_description",
                [
                    [
                        3176,
                        3185
                    ]
                ]
            ],
            [
                "T95",
                "Detailed_description",
                [
                    [
                        3252,
                        3338
                    ]
                ]
            ],
            [
                "T96",
                "Detailed_description",
                [
                    [
                        3364,
                        3409
                    ]
                ]
            ],
            [
                "T97",
                "Detailed_description",
                [
                    [
                        3411,
                        3426
                    ]
                ]
            ],
            [
                "T98",
                "Detailed_description",
                [
                    [
                        3432,
                        3467
                    ]
                ]
            ],
            [
                "T99",
                "Detailed_description",
                [
                    [
                        3469,
                        3486
                    ]
                ]
            ],
            [
                "T101",
                "Detailed_description",
                [
                    [
                        3585,
                        3595
                    ]
                ]
            ],
            [
                "T102",
                "Detailed_description",
                [
                    [
                        3668,
                        3687
                    ]
                ]
            ],
            [
                "T103",
                "Detailed_description",
                [
                    [
                        3689,
                        3736
                    ]
                ]
            ],
            [
                "T106",
                "Detailed_description",
                [
                    [
                        3788,
                        3810
                    ]
                ]
            ],
            [
                "T107",
                "Detailed_description",
                [
                    [
                        3909,
                        3932
                    ]
                ]
            ],
            [
                "T109",
                "Subject",
                [
                    [
                        4003,
                        4009
                    ]
                ]
            ],
            [
                "T110",
                "Subject",
                [
                    [
                        4020,
                        4028
                    ]
                ]
            ],
            [
                "T111",
                "Family_history",
                [
                    [
                        4071,
                        4108
                    ]
                ]
            ],
            [
                "T112",
                "Subject",
                [
                    [
                        4122,
                        4129
                    ]
                ]
            ],
            [
                "T113",
                "Family_history",
                [
                    [
                        4171,
                        4206
                    ]
                ]
            ],
            [
                "T114",
                "History",
                [
                    [
                        4247,
                        4298
                    ]
                ]
            ]
        ],
        "attributes": [
            [
                "A1",
                "POLARITY",
                "E15",
                "NEG"
            ],
            [
                "A2",
                "POLARITY",
                "E18",
                "UNCERTAIN"
            ],
            [
                "A3",
                "POLARITY",
                "E19",
                "UNCERTAIN"
            ],
            [
                "A4",
                "POLARITY",
                "E39",
                "UNCERTAIN"
            ],
            [
                "A5",
                "POLARITY",
                "E9",
                "UNCERTAIN"
            ],
            [
                "A6",
                "POLARITY",
                "E57",
                "NEG"
            ]
        ],
        "relations": [
            [
                "R1",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T3"
                    ],
                    [
                        "Arg2",
                        "E2"
                    ]
                ]
            ],
            [
                "R2",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T13"
                    ],
                    [
                        "Arg2",
                        "E6"
                    ]
                ]
            ],
            [
                "R3",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T22"
                    ],
                    [
                        "Arg2",
                        "E14"
                    ]
                ]
            ],
            [
                "R4",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T31"
                    ],
                    [
                        "Arg2",
                        "E21"
                    ]
                ]
            ],
            [
                "R5",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T32"
                    ],
                    [
                        "Arg2",
                        "E21"
                    ]
                ]
            ],
            [
                "R6",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "E25"
                    ],
                    [
                        "Arg2",
                        "E24"
                    ]
                ]
            ],
            [
                "R7",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T37"
                    ],
                    [
                        "Arg2",
                        "E24"
                    ]
                ]
            ],
            [
                "R8",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "E26"
                    ],
                    [
                        "Arg2",
                        "E24"
                    ]
                ]
            ],
            [
                "R9",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T40"
                    ],
                    [
                        "Arg2",
                        "E24"
                    ]
                ]
            ],
            [
                "R10",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T42"
                    ],
                    [
                        "Arg2",
                        "E28"
                    ]
                ]
            ],
            [
                "R11",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T44"
                    ],
                    [
                        "Arg2",
                        "E28"
                    ]
                ]
            ],
            [
                "R12",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "E27"
                    ],
                    [
                        "Arg2",
                        "E28"
                    ]
                ]
            ],
            [
                "R13",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "E29"
                    ],
                    [
                        "Arg2",
                        "E28"
                    ]
                ]
            ],
            [
                "R14",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T47"
                    ],
                    [
                        "Arg2",
                        "E31"
                    ]
                ]
            ],
            [
                "R15",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T48"
                    ],
                    [
                        "Arg2",
                        "E31"
                    ]
                ]
            ],
            [
                "R16",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T49"
                    ],
                    [
                        "Arg2",
                        "E31"
                    ]
                ]
            ],
            [
                "R17",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "E32"
                    ],
                    [
                        "Arg2",
                        "T48"
                    ]
                ]
            ],
            [
                "R18",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "E33"
                    ],
                    [
                        "Arg2",
                        "T49"
                    ]
                ]
            ],
            [
                "R19",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T53"
                    ],
                    [
                        "Arg2",
                        "E34"
                    ]
                ]
            ],
            [
                "R20",
                "IDENTICAL",
                [
                    [
                        "Arg1",
                        "E36"
                    ],
                    [
                        "Arg2",
                        "E35"
                    ]
                ]
            ],
            [
                "R21",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T60"
                    ],
                    [
                        "Arg2",
                        "T59"
                    ]
                ]
            ],
            [
                "R22",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T61"
                    ],
                    [
                        "Arg2",
                        "T59"
                    ]
                ]
            ],
            [
                "R23",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T62"
                    ],
                    [
                        "Arg2",
                        "T59"
                    ]
                ]
            ],
            [
                "R24",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T65"
                    ],
                    [
                        "Arg2",
                        "T64"
                    ]
                ]
            ],
            [
                "R25",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T68"
                    ],
                    [
                        "Arg2",
                        "T67"
                    ]
                ]
            ],
            [
                "R26",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T71"
                    ],
                    [
                        "Arg2",
                        "T70"
                    ]
                ]
            ],
            [
                "R27",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T72"
                    ],
                    [
                        "Arg2",
                        "E41"
                    ]
                ]
            ],
            [
                "R28",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T72"
                    ],
                    [
                        "Arg2",
                        "E40"
                    ]
                ]
            ],
            [
                "R29",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T80"
                    ],
                    [
                        "Arg2",
                        "E46"
                    ]
                ]
            ],
            [
                "R30",
                "IDENTICAL",
                [
                    [
                        "Arg1",
                        "E48"
                    ],
                    [
                        "Arg2",
                        "E47"
                    ]
                ]
            ],
            [
                "R31",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T83"
                    ],
                    [
                        "Arg2",
                        "E47"
                    ]
                ]
            ],
            [
                "R32",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T84"
                    ],
                    [
                        "Arg2",
                        "E47"
                    ]
                ]
            ],
            [
                "R33",
                "IDENTICAL",
                [
                    [
                        "Arg1",
                        "T85"
                    ],
                    [
                        "Arg2",
                        "T84"
                    ]
                ]
            ],
            [
                "R34",
                "IDENTICAL",
                [
                    [
                        "Arg1",
                        "E49"
                    ],
                    [
                        "Arg2",
                        "E47"
                    ]
                ]
            ],
            [
                "R35",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T86"
                    ],
                    [
                        "Arg2",
                        "E49"
                    ]
                ]
            ],
            [
                "R36",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T88"
                    ],
                    [
                        "Arg2",
                        "E49"
                    ]
                ]
            ],
            [
                "R37",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T89"
                    ],
                    [
                        "Arg2",
                        "E49"
                    ]
                ]
            ],
            [
                "R38",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T90"
                    ],
                    [
                        "Arg2",
                        "E49"
                    ]
                ]
            ],
            [
                "R39",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T92"
                    ],
                    [
                        "Arg2",
                        "E50"
                    ]
                ]
            ],
            [
                "R40",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T93"
                    ],
                    [
                        "Arg2",
                        "E50"
                    ]
                ]
            ],
            [
                "R41",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T94"
                    ],
                    [
                        "Arg2",
                        "E50"
                    ]
                ]
            ],
            [
                "R42",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T95"
                    ],
                    [
                        "Arg2",
                        "T93"
                    ]
                ]
            ],
            [
                "R43",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T96"
                    ],
                    [
                        "Arg2",
                        "E50"
                    ]
                ]
            ],
            [
                "R44",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T97"
                    ],
                    [
                        "Arg2",
                        "T96"
                    ]
                ]
            ],
            [
                "R45",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T98"
                    ],
                    [
                        "Arg2",
                        "E50"
                    ]
                ]
            ],
            [
                "R46",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T99"
                    ],
                    [
                        "Arg2",
                        "T98"
                    ]
                ]
            ],
            [
                "R47",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T101"
                    ],
                    [
                        "Arg2",
                        "E51"
                    ]
                ]
            ],
            [
                "R48",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T102"
                    ],
                    [
                        "Arg2",
                        "E51"
                    ]
                ]
            ],
            [
                "R49",
                "IDENTICAL",
                [
                    [
                        "Arg1",
                        "T103"
                    ],
                    [
                        "Arg2",
                        "T102"
                    ]
                ]
            ],
            [
                "R50",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T106"
                    ],
                    [
                        "Arg2",
                        "E52"
                    ]
                ]
            ],
            [
                "R51",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T107"
                    ],
                    [
                        "Arg2",
                        "E53"
                    ]
                ]
            ],
            [
                "R52",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T109"
                    ],
                    [
                        "Arg2",
                        "E54"
                    ]
                ]
            ],
            [
                "R53",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T110"
                    ],
                    [
                        "Arg2",
                        "E54"
                    ]
                ]
            ],
            [
                "R54",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T111"
                    ],
                    [
                        "Arg2",
                        "T110"
                    ]
                ]
            ],
            [
                "R55",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T111"
                    ],
                    [
                        "Arg2",
                        "T109"
                    ]
                ]
            ],
            [
                "R56",
                "MODIFY",
                [
                    [
                        "Arg1",
                        "T113"
                    ],
                    [
                        "Arg2",
                        "T112"
                    ]
                ]
            ],
            [
                "R57",
                "CAUSE",
                [
                    [
                        "Arg1",
                        "E56"
                    ],
                    [
                        "Arg2",
                        "E55"
                    ]
                ]
            ],
            [
                "R58",
                "AFTER",
                [
                    [
                        "Arg1",
                        "E1"
                    ],
                    [
                        "Arg2",
                        "E3"
                    ]
                ]
            ],
            [
                "R59",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E5"
                    ],
                    [
                        "Arg2",
                        "E6"
                    ]
                ]
            ],
            [
                "R60",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E6"
                    ],
                    [
                        "Arg2",
                        "E7"
                    ]
                ]
            ],
            [
                "R61",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E19"
                    ],
                    [
                        "Arg2",
                        "E13"
                    ]
                ]
            ],
            [
                "R62",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E12"
                    ],
                    [
                        "Arg2",
                        "E14"
                    ]
                ]
            ],
            [
                "R63",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E23"
                    ],
                    [
                        "Arg2",
                        "E24"
                    ]
                ]
            ],
            [
                "R64",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E26"
                    ],
                    [
                        "Arg2",
                        "E27"
                    ]
                ]
            ],
            [
                "R65",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E28"
                    ],
                    [
                        "Arg2",
                        "E30"
                    ]
                ]
            ],
            [
                "R66",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E31"
                    ],
                    [
                        "Arg2",
                        "E34"
                    ]
                ]
            ],
            [
                "R67",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E34"
                    ],
                    [
                        "Arg2",
                        "E35"
                    ]
                ]
            ],
            [
                "R68",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E37"
                    ],
                    [
                        "Arg2",
                        "E38"
                    ]
                ]
            ],
            [
                "R69",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E38"
                    ],
                    [
                        "Arg2",
                        "E39"
                    ]
                ]
            ],
            [
                "R70",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E39"
                    ],
                    [
                        "Arg2",
                        "E40"
                    ]
                ]
            ],
            [
                "R71",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E42"
                    ],
                    [
                        "Arg2",
                        "E44"
                    ]
                ]
            ],
            [
                "R72",
                "AFTER",
                [
                    [
                        "Arg1",
                        "E44"
                    ],
                    [
                        "Arg2",
                        "E45"
                    ]
                ]
            ],
            [
                "R73",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E45"
                    ],
                    [
                        "Arg2",
                        "E46"
                    ]
                ]
            ],
            [
                "R74",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E53"
                    ],
                    [
                        "Arg2",
                        "E54"
                    ]
                ]
            ],
            [
                "R75",
                "BEFORE",
                [
                    [
                        "Arg1",
                        "E54"
                    ],
                    [
                        "Arg2",
                        "E56"
                    ]
                ]
            ]
        ],
        "triggers": [
            [
                "T4",
                "Date",
                [
                    [
                        99,
                        115
                    ]
                ]
            ],
            [
                "T8",
                "Clinical_event",
                [
                    [
                        62,
                        71
                    ]
                ]
            ],
            [
                "T9",
                "Sign_symptom",
                [
                    [
                        212,
                        219
                    ]
                ]
            ],
            [
                "T10",
                "Date",
                [
                    [
                        227,
                        235
                    ]
                ]
            ],
            [
                "T11",
                "Medication",
                [
                    [
                        291,
                        316
                    ]
                ]
            ],
            [
                "T12",
                "Sign_symptom",
                [
                    [
                        377,
                        384
                    ]
                ]
            ],
            [
                "T14",
                "Date",
                [
                    [
                        393,
                        402
                    ]
                ]
            ],
            [
                "T15",
                "Sign_symptom",
                [
                    [
                        414,
                        421
                    ]
                ]
            ],
            [
                "T16",
                "Disease_disorder",
                [
                    [
                        457,
                        461
                    ]
                ]
            ],
            [
                "T17",
                "Sign_symptom",
                [
                    [
                        501,
                        522
                    ]
                ]
            ],
            [
                "T18",
                "Sign_symptom",
                [
                    [
                        528,
                        535
                    ]
                ]
            ],
            [
                "T19",
                "Date",
                [
                    [
                        689,
                        698
                    ]
                ]
            ],
            [
                "T20",
                "Sign_symptom",
                [
                    [
                        658,
                        681
                    ]
                ]
            ],
            [
                "T21",
                "Clinical_event",
                [
                    [
                        715,
                        724
                    ]
                ]
            ],
            [
                "T23",
                "Medication",
                [
                    [
                        761,
                        774
                    ]
                ]
            ],
            [
                "T25",
                "Medication",
                [
                    [
                        823,
                        833
                    ]
                ]
            ],
            [
                "T26",
                "Medication",
                [
                    [
                        849,
                        858
                    ]
                ]
            ],
            [
                "T27",
                "Sign_symptom",
                [
                    [
                        556,
                        574
                    ]
                ]
            ],
            [
                "T28",
                "Disease_disorder",
                [
                    [
                        616,
                        624
                    ]
                ]
            ],
            [
                "T29",
                "Sign_symptom",
                [
                    [
                        597,
                        608
                    ]
                ]
            ],
            [
                "T30",
                "Diagnostic_procedure",
                [
                    [
                        864,
                        867
                    ]
                ]
            ],
            [
                "T33",
                "Clinical_event",
                [
                    [
                        906,
                        918
                    ]
                ]
            ],
            [
                "T34",
                "Medication",
                [
                    [
                        941,
                        949
                    ]
                ]
            ],
            [
                "T35",
                "Clinical_event",
                [
                    [
                        969,
                        978
                    ]
                ]
            ],
            [
                "T36",
                "Therapeutic_procedure",
                [
                    [
                        1013,
                        1032
                    ]
                ]
            ],
            [
                "T38",
                "Date",
                [
                    [
                        1056,
                        1065
                    ]
                ]
            ],
            [
                "T39",
                "Date",
                [
                    [
                        1067,
                        1072
                    ]
                ]
            ],
            [
                "T41",
                "Clinical_event",
                [
                    [
                        1078,
                        1087
                    ]
                ]
            ],
            [
                "T43",
                "Therapeutic_procedure",
                [
                    [
                        1129,
                        1148
                    ]
                ]
            ],
            [
                "T45",
                "Medication",
                [
                    [
                        1192,
                        1205
                    ]
                ]
            ],
            [
                "T46",
                "Diagnostic_procedure",
                [
                    [
                        1211,
                        1214
                    ]
                ]
            ],
            [
                "T50",
                "Date",
                [
                    [
                        1251,
                        1260
                    ]
                ]
            ],
            [
                "T51",
                "Date",
                [
                    [
                        1251,
                        1257
                    ]
                ]
            ],
            [
                "T52",
                "Sign_symptom",
                [
                    [
                        1458,
                        1465
                    ]
                ]
            ],
            [
                "T54",
                "Therapeutic_procedure",
                [
                    [
                        1491,
                        1529
                    ]
                ]
            ],
            [
                "T55",
                "Therapeutic_procedure",
                [
                    [
                        1531,
                        1534
                    ]
                ]
            ],
            [
                "T56",
                "Date",
                [
                    [
                        1549,
                        1564
                    ]
                ]
            ],
            [
                "T57",
                "Sign_symptom",
                [
                    [
                        1592,
                        1617
                    ]
                ]
            ],
            [
                "T58",
                "Disease_disorder",
                [
                    [
                        1656,
                        1660
                    ]
                ]
            ],
            [
                "T73",
                "Diagnostic_procedure",
                [
                    [
                        2218,
                        2237
                    ]
                ]
            ],
            [
                "T74",
                "Clinical_event",
                [
                    [
                        2242,
                        2254
                    ]
                ]
            ],
            [
                "T75",
                "Diagnostic_procedure",
                [
                    [
                        2425,
                        2428
                    ]
                ]
            ],
            [
                "T76",
                "Diagnostic_procedure",
                [
                    [
                        2398,
                        2419
                    ]
                ]
            ],
            [
                "T77",
                "Diagnostic_procedure",
                [
                    [
                        2430,
                        2443
                    ]
                ]
            ],
            [
                "T78",
                "Clinical_event",
                [
                    [
                        2509,
                        2527
                    ]
                ]
            ],
            [
                "T79",
                "Diagnostic_procedure",
                [
                    [
                        2599,
                        2610
                    ]
                ]
            ],
            [
                "T81",
                "Diagnostic_procedure",
                [
                    [
                        2915,
                        2940
                    ]
                ]
            ],
            [
                "T82",
                "Diagnostic_procedure",
                [
                    [
                        2942,
                        2945
                    ]
                ]
            ],
            [
                "T87",
                "Coreference",
                [
                    [
                        3053,
                        3070
                    ]
                ]
            ],
            [
                "T91",
                "Diagnostic_procedure",
                [
                    [
                        3217,
                        3227
                    ]
                ]
            ],
            [
                "T100",
                "Diagnostic_procedure",
                [
                    [
                        3489,
                        3505
                    ]
                ]
            ],
            [
                "T104",
                "Sign_symptom",
                [
                    [
                        3759,
                        3786
                    ]
                ]
            ],
            [
                "T105",
                "Sign_symptom",
                [
                    [
                        3882,
                        3907
                    ]
                ]
            ],
            [
                "T108",
                "Diagnostic_procedure",
                [
                    [
                        3978,
                        3995
                    ]
                ]
            ],
            [
                "T115",
                "Disease_disorder",
                [
                    [
                        4389,
                        4394
                    ]
                ]
            ],
            [
                "T116",
                "Sign_symptom",
                [
                    [
                        4326,
                        4353
                    ]
                ]
            ],
            [
                "T117",
                "Sign_symptom",
                [
                    [
                        4425,
                        4473
                    ]
                ]
            ]
        ],
        "events": [
            [
                "E1",
                "T4",
                []
            ],
            [
                "E2",
                "T8",
                []
            ],
            [
                "E3",
                "T9",
                []
            ],
            [
                "E4",
                "T10",
                []
            ],
            [
                "E5",
                "T11",
                []
            ],
            [
                "E6",
                "T12",
                []
            ],
            [
                "E7",
                "T14",
                []
            ],
            [
                "E8",
                "T15",
                []
            ],
            [
                "E9",
                "T16",
                []
            ],
            [
                "E10",
                "T17",
                []
            ],
            [
                "E11",
                "T18",
                []
            ],
            [
                "E12",
                "T19",
                []
            ],
            [
                "E13",
                "T20",
                []
            ],
            [
                "E14",
                "T21",
                []
            ],
            [
                "E15",
                "T23",
                []
            ],
            [
                "E16",
                "T25",
                []
            ],
            [
                "E17",
                "T26",
                []
            ],
            [
                "E18",
                "T27",
                []
            ],
            [
                "E19",
                "T28",
                []
            ],
            [
                "E20",
                "T29",
                []
            ],
            [
                "E21",
                "T30",
                []
            ],
            [
                "E22",
                "T33",
                []
            ],
            [
                "E23",
                "T34",
                []
            ],
            [
                "E24",
                "T35",
                []
            ],
            [
                "E25",
                "T36",
                []
            ],
            [
                "E26",
                "T38",
                []
            ],
            [
                "E27",
                "T39",
                []
            ],
            [
                "E28",
                "T41",
                []
            ],
            [
                "E29",
                "T43",
                []
            ],
            [
                "E30",
                "T45",
                []
            ],
            [
                "E31",
                "T46",
                []
            ],
            [
                "E32",
                "T50",
                []
            ],
            [
                "E33",
                "T51",
                []
            ],
            [
                "E34",
                "T52",
                []
            ],
            [
                "E35",
                "T54",
                []
            ],
            [
                "E36",
                "T55",
                []
            ],
            [
                "E37",
                "T56",
                []
            ],
            [
                "E38",
                "T57",
                []
            ],
            [
                "E39",
                "T58",
                []
            ],
            [
                "E40",
                "T73",
                []
            ],
            [
                "E41",
                "T74",
                []
            ],
            [
                "E42",
                "T75",
                []
            ],
            [
                "E43",
                "T76",
                []
            ],
            [
                "E44",
                "T77",
                []
            ],
            [
                "E45",
                "T78",
                []
            ],
            [
                "E46",
                "T79",
                []
            ],
            [
                "E47",
                "T81",
                []
            ],
            [
                "E48",
                "T82",
                []
            ],
            [
                "E49",
                "T87",
                []
            ],
            [
                "E50",
                "T91",
                []
            ],
            [
                "E51",
                "T100",
                []
            ],
            [
                "E52",
                "T104",
                []
            ],
            [
                "E53",
                "T105",
                []
            ],
            [
                "E54",
                "T108",
                []
            ],
            [
                "E55",
                "T115",
                []
            ],
            [
                "E56",
                "T116",
                []
            ],
            [
                "E57",
                "T117",
                []
            ]
        ],
        "equivs": [
            [
                "*",
                "OVERLAP",
                "E2",
                "E1"
            ],
            [
                "*",
                "OVERLAP",
                "E3",
                "E4",
                "E5"
            ],
            [
                "*",
                "OVERLAP",
                "E7",
                "E8",
                "E9",
                "E10",
                "E11",
                "E18",
                "E20",
                "E19"
            ],
            [
                "*",
                "OVERLAP",
                "E13",
                "E12"
            ],
            [
                "*",
                "OVERLAP",
                "E14",
                "E15",
                "E16",
                "E17",
                "E21",
                "E22",
                "E23"
            ],
            [
                "*",
                "OVERLAP",
                "E24",
                "E26"
            ],
            [
                "*",
                "OVERLAP",
                "E27",
                "E28"
            ],
            [
                "*",
                "OVERLAP",
                "E30",
                "E31"
            ],
            [
                "*",
                "OVERLAP",
                "E35",
                "E37"
            ],
            [
                "*",
                "OVERLAP",
                "E40",
                "E43",
                "E42"
            ],
            [
                "*",
                "OVERLAP",
                "E46",
                "E47",
                "E50",
                "E51",
                "E52",
                "E53"
            ],
            [
                "*",
                "OVERLAP",
                "E56",
                "E57"
            ]
        ],
        "comments": [
            [
                "E9",
                "AnnotatorNotes",
                "Jervell and Lange-Nielsen syndrome"
            ],
            [
                "T59",
                "AnnotatorNotes",
                "Note that most material in this sentence is about the children, not the patient"
            ],
            [
                "T69",
                "AnnotatorNotes",
                "Medically relevant for the patient, not her parents"
            ]
        ],
        "graph_index_data_before": [
            [
                291,
                316,
                "T11",
                377,
                384,
                "T12"
            ],
            [
                377,
                384,
                "T12",
                393,
                402,
                "T14"
            ],
            [
                616,
                624,
                "T28",
                658,
                681,
                "T20"
            ],
            [
                689,
                698,
                "T19",
                715,
                724,
                "T21"
            ],
            [
                941,
                949,
                "T34",
                969,
                978,
                "T35"
            ],
            [
                1056,
                1065,
                "T38",
                1067,
                1072,
                "T39"
            ],
            [
                1078,
                1087,
                "T41",
                1192,
                1205,
                "T45"
            ],
            [
                1211,
                1214,
                "T46",
                1458,
                1465,
                "T52"
            ],
            [
                1458,
                1465,
                "T52",
                1491,
                1529,
                "T54"
            ],
            [
                1549,
                1564,
                "T56",
                1592,
                1617,
                "T57"
            ],
            [
                1592,
                1617,
                "T57",
                1656,
                1660,
                "T58"
            ],
            [
                1656,
                1660,
                "T58",
                2218,
                2237,
                "T73"
            ],
            [
                2425,
                2428,
                "T75",
                2430,
                2443,
                "T77"
            ],
            [
                2509,
                2527,
                "T78",
                2599,
                2610,
                "T79"
            ],
            [
                3882,
                3907,
                "T105",
                3978,
                3995,
                "T108"
            ],
            [
                3978,
                3995,
                "T108",
                4326,
                4353,
                "T116"
            ]
        ],
        "graph_text_data_before": [
            "anti-epilepsy medications syncope",
            "syncope age of 13",
            "epilepsy subarachnoid hemorrhage",
            "age of 29 presented",
            "atenolol delivered",
            "age of 35 At 37",
            "delivered beta-blockers",
            "QTc syncope",
            "syncope implantable cardioverter defibrillator",
            "38 years of age stable clinical condition",
            "stable clinical condition JLNS",
            "JLNS Clinical evaluation",
            "ECG Blood samples",
            "genetic counseling Genomic DNA",
            "homozygous common variant Genetic screening",
            "Genetic screening homozygous nonsense variant"
        ],
        "text": "The proband (II-2 in Fig.2) is a 45-year old woman, who first presented to our university hospital at the age of 35 and was referred to us because of her pregnancy.\nShe has congenital deafness, first experienced syncope at the age of 3, and was diagnosed with epilepsy.\nShe was treated with anti-epilepsy medications; however, she subsequently experienced several instances of syncope.\nAt the age of 13, she had a syncope event, and was suspected of having JLNS because of her congenital deafness and prolonged QT interval.\nHer syncope was diagnosed as an arrhythmic episode when she was aware of tachycardia and as epilepsy when she was not.\nShe also had a subarachnoid hemorrhage at the age of 29.\nWhen she first presented at our hospital, she was not taking beta-blockers, because of a history of asthma, but was taking mexiletine in addition to phenytoin.\nHer QTc was found to be prolonged (584 ms) at presentation and administration of atenolol was initiated.\nShe delivered her baby (III-1 in Fig.2) through Caesarean operation at our hospital at the age of 35.\nAt 37, she delivered her second baby (III-2 in Fig.2) through Caesarean operation at our hospital.\nDespite administration of beta-blockers, her QTc remained prolonged (600 msec at the age of 37, 780 msec at 44) (Figs.2 and \u200b3a), which is not unexpected because treatment with beta-blockers in LQTS1 is not expected to overtly reduce QTc [18].\nHowever, she continued to experience occasional syncope and finally underwent an implantable cardioverter defibrillator (ICD) operation at 38 years of age.\nSubsequently, she is in a stable clinical condition.\nBecause the proband was suspected of JLNS and both infants had a measured QTc of 500 ms or greater within 1 month after birth, beta blockers were initiated and both children remain in stable condition at ages 10 and 8 (Figs.2 and 3b, c).\nQTc of the son (III-1 in Fig.2) was measured as 500 ms one month after birth, while the QTc of his sister (III-2) was 530 ms at birth.\nThe father (I-1) and mother (I-2) of the proband were first cousins.\nThere is no history of sudden unexplained syncope or death of children or adults in the immediate family members, despite the prolonged QTc of the children.\nClinical evaluation and consultation of the proband and her family members were performed at Chiba University Hospital.\nClinical phenotypes were deduced from the clinical history, physical examinations, and ECG.\nBlood samples were collected from the proband and her family members following genetic counseling, and written informed consent was obtained prior to sample collection.\nGenomic DNA was isolated from peripheral blood lymphocytes according to established protocols at our laboratory [19].\nEntire coding exons, including the intronic boundaries of the genes, of KCNQ1 (NCBI ref: NM_000218) and other LQT causative genes (KCNH2, SCN5A, KCNE1, KCNE2, KCNJ2, SCN4B, KCNJ5) were amplified by polymerase chain reaction (PCR), according to established protocols in our laboratory.\nBriefly, 30\u2013100 ng of genomic DNA was subjected to PCR amplification with DNA polymerase (PrimeSTAR GXL DNA Polymerase; Takara Bio Inc., Kusatsu, Japan) and primer sets.\nThe amplicons were subjected to conventional sequencing with Sanger sequencers (Applied Biosystems 3730/3130 DNA analyzers; Thermo Fisher Scientific, Waltham, MA, USA).\nThe sequence data were processed with Gene Codes Sequencher Software (Takara Bio Inc.) and mapped to the human genome sequence (build GRCh37/hg19).\nGenetic analysis was performed to screen all coding exons and the exon\u2013intron boundaries of the KCNQ1 gene (NCBI ref: NM_000218.2, NP_000209.2) with concurrent screening of other LQT causative genes (KCNH2, SCN5A, KCNE1, KCNE2, KCNJ2, SCN4B, KCNJ5).\nWe detected a novel homozygous nonsense variant, NM_000218.2:c.115G\u2009>\u2009T (p.Glu39X, in exon 1a), in the KCNQ1 gene of the proband, as well as a homozygous common variant (NM_000218.2:c.1343C\u2009>\u2009G, p.Pro448Arg) (Additional file 1: Table S1).\nGenetic screening of her mother (I-2) and children (III-1 and III-2) revealed that they were heterozygous for the nonsense variant (Fig.2).\nHer husband (II-3) was also screened and found to be heterozygous for the common variant (NM_000218.2:c.1343C\u2009>\u2009G, p.Pro448Arg).\nThe proband is a child from a first-cousin marriage, and we have concluded the homozygous nonsense variant in the proband is the cause of her JLNS1.\nThe proband was negative for pathogenic variants in other LQT causative genes, including the KCNE1 gene (Additional file 1: Table S1).",
        "action": "getDocument",
        "createdAt": {
            "$date": "2019-04-09T00:56:27.611Z"
        },
        "updatedAt": {
            "$date": "2019-04-09T00:56:27.611Z"
        },
        "__v": 0
      }
    };
  }

  render(){
    
    
    var i;
    // Create the Elements (Nodes) to be visualized
    var elements = [
       // { data: { id: 'one', label: 'Node 1' } },
       // { data: { id: 'two', label: 'Node 2' } },
       // { data: { source: 'one', target: 'two', label: 'Edge from Node1 to Node2' } }
    ];

    var elements2 = [];

    // From Entities
    var nID2index = new Map();
    for (i=0; i < this.state.caseReport.entities.length; i++) {
      const nodeID = this.state.caseReport.entities[i][0];
      const nodeTextSIndex = this.state.caseReport.entities[i][2][0][0];
      const nodeTextEIndex = this.state.caseReport.entities[i][2][0][1];
      // const nodeText = this.state.caseReport.text.substring(nodeTextSIndex,nodeTextEIndex);
      // elements.push( {
      //   data: {
      //     id: nodeID, 
      //     label: nodeText
      //   }
      // });
      nID2index.set(nodeID, [nodeTextSIndex, nodeTextEIndex]);
    }
    // From Triggers
    for (i=0; i < this.state.caseReport.triggers.length; i++) {
      const nodeID = this.state.caseReport.triggers[i][0];
      const nodeTextSIndex = this.state.caseReport.triggers[i][2][0][0];
      const nodeTextEIndex = this.state.caseReport.triggers[i][2][0][1];
      // const nodeText = this.state.caseReport.text.substring(nodeTextSIndex,nodeTextEIndex);
      // elements.push( {
      //   data: {
      //     id: nodeID, 
      //     label: nodeText
      //   }
      // });
      nID2index.set(nodeID, [nodeTextSIndex, nodeTextEIndex]);
    }

    // Create the Edges to be visualized
    // First map all events to a node
    var eID2nID = new Map();
    for (i=0; i<this.state.caseReport.events.length; i++) {
      const eventID = this.state.caseReport.events[i][0];
      const nodeID = this.state.caseReport.events[i][1];
      eID2nID.set(eventID, nodeID);
    }
    // From Relatiosn
    var nodeSet = new Set();
    for (var i=0; i < this.state.caseReport.relations.length; i++) {
      const eventID_1 = this.state.caseReport.relations[i][2][0][1];
      const eventID_2 = this.state.caseReport.relations[i][2][1][1];
      const event_label = this.state.caseReport.relations[i][1];
      // if (event_label=='BEFORE') {
        // continue;
      // }
      const sourcID = eID2nID.has(eventID_1) ? eID2nID.get(eventID_1) : eventID_1;
      const targetID = eID2nID.has(eventID_2) ? eID2nID.get(eventID_2) : eventID_2;

      var nodeText;
      if (!nodeSet.has(sourcID)) {
        nodeText = this.state.caseReport.text.substring(nID2index.get(sourcID)[0], nID2index.get(sourcID)[1]);
        nodeText = nodeText.length>15 ? nodeText.substring(0,15) : nodeText;
        elements.push( {
          data: {
            id: sourcID,
            label: nodeText
          }
        });
        nodeSet.add(sourcID);
      }

      if (!nodeSet.has(targetID)) {
        nodeText = this.state.caseReport.text.substring(nID2index.get(sourcID)[0], nID2index.get(sourcID)[1]);
        nodeText = nodeText.length>15 ? nodeText.substring(0,15) : nodeText;
        elements.push( {
          data: {
            id: targetID,
            label: nodeText
          }
        });
        nodeSet.add(targetID);
      }
      var color="rgb(1, 136, 203)";
      // if (event_label=='BEFORE'){
      //   color = 'red';
      // }
      // else if (event_label=='MODIFY') {
      //   color = 'blue';
      // }
      // else if (event_label=='IDENTICAL') {
      //   color = 'green';
      // }
      elements.push( {
        data: {
          source: sourcID,
          target: targetID,
          label: event_label,
          arrow: 'triangle',
          c: color
        }
      });
      // }

      // else if (event_label=='MODIFY') {
      //   const sourcID = eID2nID.has(eventID_1) ? eID2nID.get(eventID_1) : eventID_1;
      //   const targetID = eID2nID.has(eventID_2) ? eID2nID.get(eventID_2) : eventID_2;

      // // if (!nodeSet.has(sourcID)) {
      //   elements2.push( {
      //     data: {
      //       id: sourcID,
      //       label: this.state.caseReport.text.substring(nID2index.get(sourcID)[0], nID2index.get(sourcID)[1])
      //     }
      //   });
      //   nodeSet.add(sourcID);
      // // }

      // // if (!nodeSet.has(targetID)) {
      //   elements2.push( {
      //     data: {
      //       id: targetID,
      //       label: this.state.caseReport.text.substring(nID2index.get(targetID)[0], nID2index.get(targetID)[1])
      //     }
      //   });
      //   nodeSet.add(targetID);
      // // }

      //   elements2.push( {
      //     data: {
      //       source: sourcID,
      //       target: targetID,
      //       label: event_label,
      //       arrow: 'triangle'
      //     }
      //   });
      // }
    }
    // Layout
    const layout = {
      name: 'dagre',
      nodeSep: 100,
      nodeDimensionsIncludeLabels: true
      // ranker: "longest-path"
      // name: 'breadthfirst',
      // directed: true,
      // padding: 10
    };
    

    // elements.push( { data: { id: 'three', label: 'Node 3' }, position: { x: 500, y: 250 } } );
    // elements.push( {data: { source: 'three', target: 'two', label: 'Edge from Node3 to Node2'}});
    return (
      <div>
      <div>
      <CytoscapeComponent elements={elements} style={ { width: '1000px', height: '500px'}} layout={layout} stylesheet={[
        {
          "selector": "node",
          "style": {
            "content": "data(label)",
            "text-valign": "center",
            "text-halign": "center",
            // "text-font-size": 100,
            // "width": 40,
            // "height": 40,
            "background-color": "rgb(244, 149, 65)",              // node color
            "text-outline-color": "rgb(244, 149, 65)",
            "text-outline-opacity": 1,
            "text-outline-width": 0,
            "color": "black",                                     // text color
            "overlay-color": "#fff"
          }
        },
        {
          "selector": "edge",
          "style": {
            "width": 3,
            "curve-style": "straight"
          }
        },
        {
          "selector": "edge[arrow]",
          "style": {
            "target-arrow-shape": "data(arrow)",
            "line-color": "data(c)"
          }
        }
      ]} ></CytoscapeComponent>
      </div>
      </div>
    );
  }
}
export default VisualizeCaseReport;
