const express = require('express');
const axios = require('axios');
const Data = require("./models/mongo/data");
const CaseReport = require("./models/mongo/case_report");
var searchModule = require('./search.js');

//在这里我们可以建立controller，然后在controller里做api要做的事情
// var HomeController = require('./controllers/home_controller.js');

module.exports = function(app) {
    // append /api for our http requests
    var router = express.Router();
    app.use("/api", router);


    // 这样我们call api的时候可以把前后端交互的逻辑移到controller里,比如
    // app.get('/', HomeController.index);
    // app.get('/getData', DataController.getData);等等

    /* ------------------------- Database Routers ------------------------------ */
    // this is our get method
    // this method fetches all available data in our database
    router.get("/getData", (req, res) => {
        Data.find((err, data) => {
            if (err) return res.json({ success: false, error: err });

            return res.json({ success: true, data: data });
        });
    });

    // this is our update method
    // this method overwrites existing data in our database
    router.post("/updateData", (req, res) => {
        const { id, update } = req.body;

        Data.findOneAndUpdate(id, update, err => {
            if (err) return res.json({ success: false, error: err });
            return res.json({ success: true });
        });
    });

    // this is our delete method
    // this method removes existing data in our database
    router.delete("/deleteData", (req, res) => {
        const { id } = req.body;

        Data.findOneAndDelete(id, err => {
            if (err) return res.send(err);
            return res.json({ success: true });
        });
    });

    // this is our create methid
    // this method adds new data in our database
    router.post("/putData", (req, res) => {
        let data = new Data();
        // console.log(req.body);
        const { id, message } = req.body;

        if ((!id && id !== 0) || !message) {
            return res.json({
                success: false,
                error: "INVALID INPUTS"
            });
        }
        data.message = message;
        data.id = id;
        data.save(err => {
            if (err) return res.json({ success: false, error: err });
            return res.json({ success: true });
        });
    });

    /* --------------------------------- Search APIs --------------------------------------- */
    // this is the method for basic text search on the data message
    router.post("/searchData", (req, res) => {
        const {id, searchKey} = req.body;
        // console.log(req);
        // console.log(searchKey);
        // console.log('searchData api message');

        var re = new RegExp(searchKey);

        Data.find( { message:re }, (err, data) => {
            if (err) return res.send(err);
            return res.json({ success : true, data: data });
        });
    });

    router.post('/searchDataES',(req, res) => {
        // console.log(req.body);
        const {searchKey} = req.body;
        // var req_body = new RegExp(searchKey);
        searchModule.search(searchKey, function(data) {
            console.log(data,'server')
            for (i = 0; i < data.length; i++) { 
              data[i]._source.content = data[i]._source.content.substring(0,350)+'...';
            }
            return res.json({ success : true, data: data });
        });
    });
    /* ------------------------- Machine Learning API Routers ------------------------------ */
    router.post("/getPrediction", (req, res) => {
        const params = req.body.data;
        // console.log(params);
        axios.get('http://127.0.0.1:5000/', { params })
            .then(response => {
                data = response.data
                console.log(data);
                return res.json(data);
            })
            .catch(error => { console.log(error); });
    });

    /* --------------------------------- CaseReport APIs ----------------------------------- */
    // getCaseReport
    // this get API fetches all case reports stored in the mongo db
    // router.get("/getCaseReport", (req, res) => {
    //     CaseReport.find((err, data) => {
    //         if (err) return res.json({ success: false, error: err });
    //         return res.json({ success: true, data: data });
    //     });
    // });

    router.get("/getCaseReport", (req, res) => {
        const r = Math.floor(Math.random() * 10);
        let reportDetails = null;
        if (r >= 5) {
            reportDetails = {
    "_id": {
        "$oid": "5c8eea55ca49b8479b8938cd"
    },
    "messages": [],
    "source_files": [
        "ann",
        "txt"
    ],
    "modifications": [],
    "normalizations": [],
    "entities": [
        [
            "T1",
            "Age",
            [
                [
                    8,
                    19
                ]
            ]
        ],
        [
            "T2",
            "History",
            [
                [
                    20,
                    38
                ]
            ]
        ],
        [
            "T3",
            "Sex",
            [
                [
                    39,
                    42
                ]
            ]
        ],
        [
            "T10",
            "Frequency",
            [
                [
                    127,
                    145
                ]
            ]
        ],
        [
            "T11",
            "Detailed_description",
            [
                [
                    154,
                    180
                ]
            ]
        ],
        [
            "T14",
            "Biological_structure",
            [
                [
                    251,
                    260
                ]
            ]
        ],
        [
            "T15",
            "Detailed_description",
            [
                [
                    238,
                    250
                ]
            ]
        ],
        [
            "T16",
            "Lab_value",
            [
                [
                    228,
                    237
                ]
            ]
        ],
        [
            "T17",
            "Biological_structure",
            [
                [
                    301,
                    320
                ]
            ]
        ],
        [
            "T18",
            "Detailed_description",
            [
                [
                    326,
                    350
                ]
            ]
        ],
        [
            "T27",
            "Detailed_description",
            [
                [
                    542,
                    553
                ]
            ]
        ],
        [
            "T29",
            "Biological_structure",
            [
                [
                    573,
                    586
                ]
            ]
        ],
        [
            "T31",
            "Biological_structure",
            [
                [
                    658,
                    673
                ]
            ]
        ],
        [
            "T35",
            "Biological_structure",
            [
                [
                    746,
                    761
                ]
            ]
        ],
        [
            "T36",
            "Biological_structure",
            [
                [
                    793,
                    805
                ]
            ]
        ],
        [
            "T37",
            "Biological_structure",
            [
                [
                    844,
                    859
                ]
            ]
        ],
        [
            "T38",
            "Biological_structure",
            [
                [
                    814,
                    819
                ]
            ]
        ],
        [
            "T40",
            "Biological_structure",
            [
                [
                    874,
                    906
                ]
            ]
        ],
        [
            "T42",
            "Biological_structure",
            [
                [
                    950,
                    964
                ]
            ]
        ],
        [
            "T44",
            "Detailed_description",
            [
                [
                    1002,
                    1010
                ]
            ]
        ],
        [
            "T45",
            "Detailed_description",
            [
                [
                    1028,
                    1040
                ]
            ]
        ],
        [
            "T49",
            "Biological_structure",
            [
                [
                    1120,
                    1131
                ]
            ]
        ],
        [
            "T52",
            "Biological_structure",
            [
                [
                    1212,
                    1229
                ]
            ]
        ],
        [
            "T54",
            "Detailed_description",
            [
                [
                    1243,
                    1257
                ]
            ]
        ],
        [
            "T62",
            "Detailed_description",
            [
                [
                    1471,
                    1495
                ]
            ]
        ],
        [
            "T65",
            "Biological_structure",
            [
                [
                    1576,
                    1591
                ]
            ]
        ]
    ],
    "attributes": [
        [
            "A1",
            "POLARITY",
            "E35",
            "NEG"
        ]
    ],
    "relations": [
        [
            "R1",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E5"
                ],
                [
                    "Arg2",
                    "E4"
                ]
            ]
        ],
        [
            "R2",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E6"
                ],
                [
                    "Arg2",
                    "E5"
                ]
            ]
        ],
        [
            "R3",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T10"
                ],
                [
                    "Arg2",
                    "E5"
                ]
            ]
        ],
        [
            "R4",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T11"
                ],
                [
                    "Arg2",
                    "E5"
                ]
            ]
        ],
        [
            "R5",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T14"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R6",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T15"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R7",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T16"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R8",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T17"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R9",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T18"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R11",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E11"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R12",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E12"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R14",
            "CAUSE",
            [
                [
                    "Arg1",
                    "E14"
                ],
                [
                    "Arg2",
                    "E13"
                ]
            ]
        ],
        [
            "R15",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T27"
                ],
                [
                    "Arg2",
                    "E14"
                ]
            ]
        ],
        [
            "R16",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T29"
                ],
                [
                    "Arg2",
                    "E15"
                ]
            ]
        ],
        [
            "R17",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T31"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R18",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E18"
                ],
                [
                    "Arg2",
                    "T31"
                ]
            ]
        ],
        [
            "R19",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E18"
                ],
                [
                    "Arg2",
                    "E17"
                ]
            ]
        ],
        [
            "R20",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T35"
                ],
                [
                    "Arg2",
                    "E19"
                ]
            ]
        ],
        [
            "R21",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T38"
                ],
                [
                    "Arg2",
                    "T37"
                ]
            ]
        ],
        [
            "R22",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T37"
                ],
                [
                    "Arg2",
                    "E19"
                ]
            ]
        ],
        [
            "R23",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T36"
                ],
                [
                    "Arg2",
                    "E19"
                ]
            ]
        ],
        [
            "R24",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T40"
                ],
                [
                    "Arg2",
                    "E20"
                ]
            ]
        ],
        [
            "R25",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T42"
                ],
                [
                    "Arg2",
                    "E21"
                ]
            ]
        ],
        [
            "R26",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T44"
                ],
                [
                    "Arg2",
                    "E22"
                ]
            ]
        ],
        [
            "R27",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T45"
                ],
                [
                    "Arg2",
                    "E22"
                ]
            ]
        ],
        [
            "R28",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T49"
                ],
                [
                    "Arg2",
                    "E25"
                ]
            ]
        ],
        [
            "R29",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T52"
                ],
                [
                    "Arg2",
                    "E27"
                ]
            ]
        ],
        [
            "R30",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T54"
                ],
                [
                    "Arg2",
                    "E28"
                ]
            ]
        ],
        [
            "R31",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E29"
                ],
                [
                    "Arg2",
                    "E28"
                ]
            ]
        ],
        [
            "R35",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T62"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ],
        [
            "R36",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T65"
                ],
                [
                    "Arg2",
                    "E34"
                ]
            ]
        ],
        [
            "R37",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E2"
                ],
                [
                    "Arg2",
                    "E1"
                ]
            ]
        ],
        [
            "R38",
            "AFTER",
            [
                [
                    "Arg1",
                    "E1"
                ],
                [
                    "Arg2",
                    "E3"
                ]
            ]
        ],
        [
            "R39",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E8"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R40",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E25"
                ],
                [
                    "Arg2",
                    "E26"
                ]
            ]
        ],
        [
            "R41",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E27"
                ],
                [
                    "Arg2",
                    "E28"
                ]
            ]
        ],
        [
            "R42",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E28"
                ],
                [
                    "Arg2",
                    "E30"
                ]
            ]
        ],
        [
            "R43",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E34"
                ],
                [
                    "Arg2",
                    "E35"
                ]
            ]
        ],
        [
            "R10",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E38"
                ],
                [
                    "Arg2",
                    "E9"
                ]
            ]
        ],
        [
            "R13",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E39"
                ],
                [
                    "Arg2",
                    "E12"
                ]
            ]
        ],
        [
            "R32",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E40"
                ],
                [
                    "Arg2",
                    "E31"
                ]
            ]
        ],
        [
            "R33",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E41"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ],
        [
            "R34",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E42"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ]
    ],
    "triggers": [
        [
            "T4",
            "Clinical_event",
            [
                [
                    43,
                    52
                ]
            ]
        ],
        [
            "T5",
            "Sign_symptom",
            [
                [
                    31,
                    38
                ]
            ]
        ],
        [
            "T6",
            "Duration",
            [
                [
                    60,
                    66
                ]
            ]
        ],
        [
            "T7",
            "Sign_symptom",
            [
                [
                    78,
                    90
                ]
            ]
        ],
        [
            "T8",
            "Coreference",
            [
                [
                    96,
                    104
                ]
            ]
        ],
        [
            "T9",
            "Clinical_event",
            [
                [
                    121,
                    125
                ]
            ]
        ],
        [
            "T12",
            "Sign_symptom",
            [
                [
                    206,
                    213
                ]
            ]
        ],
        [
            "T13",
            "Sign_symptom",
            [
                [
                    261,
                    281
                ]
            ]
        ],
        [
            "T19",
            "Diagnostic_procedure",
            [
                [
                    353,
                    373
                ]
            ]
        ],
        [
            "T21",
            "Diagnostic_procedure",
            [
                [
                    408,
                    425
                ]
            ]
        ],
        [
            "T22",
            "Diagnostic_procedure",
            [
                [
                    427,
                    430
                ]
            ]
        ],
        [
            "T23",
            "Diagnostic_procedure",
            [
                [
                    448,
                    460
                ]
            ]
        ],
        [
            "T25",
            "Sign_symptom",
            [
                [
                    467,
                    513
                ]
            ]
        ],
        [
            "T26",
            "Disease_disorder",
            [
                [
                    554,
                    571
                ]
            ]
        ],
        [
            "T28",
            "Diagnostic_procedure",
            [
                [
                    587,
                    603
                ]
            ]
        ],
        [
            "T30",
            "Disease_disorder",
            [
                [
                    633,
                    650
                ]
            ]
        ],
        [
            "T32",
            "Sign_symptom",
            [
                [
                    680,
                    699
                ]
            ]
        ],
        [
            "T33",
            "Coreference",
            [
                [
                    707,
                    712
                ]
            ]
        ],
        [
            "T34",
            "Disease_disorder",
            [
                [
                    734,
                    744
                ]
            ]
        ],
        [
            "T39",
            "Sign_symptom",
            [
                [
                    911,
                    920
                ]
            ]
        ],
        [
            "T41",
            "Sign_symptom",
            [
                [
                    969,
                    980
                ]
            ]
        ],
        [
            "T43",
            "Diagnostic_procedure",
            [
                [
                    1011,
                    1027
                ]
            ]
        ],
        [
            "T46",
            "Disease_disorder",
            [
                [
                    1052,
                    1072
                ]
            ]
        ],
        [
            "T47",
            "Sign_symptom",
            [
                [
                    1078,
                    1100
                ]
            ]
        ],
        [
            "T48",
            "Sign_symptom",
            [
                [
                    1105,
                    1112
                ]
            ]
        ],
        [
            "T50",
            "Diagnostic_procedure",
            [
                [
                    1167,
                    1191
                ]
            ]
        ],
        [
            "T51",
            "Diagnostic_procedure",
            [
                [
                    1197,
                    1204
                ]
            ]
        ],
        [
            "T53",
            "Therapeutic_procedure",
            [
                [
                    1258,
                    1266
                ]
            ]
        ],
        [
            "T55",
            "Therapeutic_procedure",
            [
                [
                    1363,
                    1380
                ]
            ]
        ],
        [
            "T56",
            "Diagnostic_procedure",
            [
                [
                    1401,
                    1404
                ]
            ]
        ],
        [
            "T57",
            "Diagnostic_procedure",
            [
                [
                    1424,
                    1435
                ]
            ]
        ],
        [
            "T59",
            "Diagnostic_procedure",
            [
                [
                    1456,
                    1467
                ]
            ]
        ],
        [
            "T63",
            "Disease_disorder",
            [
                [
                    1528,
                    1555
                ]
            ]
        ],
        [
            "T64",
            "Disease_disorder",
            [
                [
                    1564,
                    1574
                ]
            ]
        ],
        [
            "T66",
            "Sign_symptom",
            [
                [
                    1631,
                    1643
                ]
            ]
        ],
        [
            "T67",
            "Clinical_event",
            [
                [
                    1647,
                    1656
                ]
            ]
        ],
        [
            "T68",
            "Date",
            [
                [
                    1657,
                    1671
                ]
            ]
        ],
        [
            "T20",
            "Lab_value",
            [
                [
                    382,
                    394
                ]
            ]
        ],
        [
            "T24",
            "Lab_value",
            [
                [
                    441,
                    447
                ]
            ]
        ],
        [
            "T58",
            "Lab_value",
            [
                [
                    1414,
                    1423
                ]
            ]
        ],
        [
            "T60",
            "Lab_value",
            [
                [
                    1447,
                    1455
                ]
            ]
        ],
        [
            "T61",
            "Lab_value",
            [
                [
                    1443,
                    1446
                ]
            ]
        ]
    ],
    "events": [
        [
            "E1",
            "T4",
            []
        ],
        [
            "E2",
            "T5",
            []
        ],
        [
            "E3",
            "T6",
            []
        ],
        [
            "E4",
            "T7",
            []
        ],
        [
            "E5",
            "T8",
            []
        ],
        [
            "E6",
            "T9",
            []
        ],
        [
            "E8",
            "T12",
            []
        ],
        [
            "E7",
            "T13",
            []
        ],
        [
            "E9",
            "T19",
            []
        ],
        [
            "E10",
            "T21",
            []
        ],
        [
            "E11",
            "T22",
            []
        ],
        [
            "E12",
            "T23",
            []
        ],
        [
            "E13",
            "T25",
            []
        ],
        [
            "E14",
            "T26",
            []
        ],
        [
            "E15",
            "T28",
            []
        ],
        [
            "E16",
            "T30",
            []
        ],
        [
            "E17",
            "T32",
            []
        ],
        [
            "E18",
            "T33",
            []
        ],
        [
            "E19",
            "T34",
            []
        ],
        [
            "E20",
            "T39",
            []
        ],
        [
            "E21",
            "T41",
            []
        ],
        [
            "E22",
            "T43",
            []
        ],
        [
            "E23",
            "T46",
            []
        ],
        [
            "E24",
            "T47",
            []
        ],
        [
            "E25",
            "T48",
            []
        ],
        [
            "E26",
            "T50",
            []
        ],
        [
            "E27",
            "T51",
            []
        ],
        [
            "E28",
            "T53",
            []
        ],
        [
            "E29",
            "T55",
            []
        ],
        [
            "E30",
            "T56",
            []
        ],
        [
            "E31",
            "T57",
            []
        ],
        [
            "E32",
            "T59",
            []
        ],
        [
            "E33",
            "T63",
            []
        ],
        [
            "E34",
            "T64",
            []
        ],
        [
            "E35",
            "T66",
            []
        ],
        [
            "E36",
            "T67",
            []
        ],
        [
            "E37",
            "T68",
            []
        ],
        [
            "E38",
            "T20",
            []
        ],
        [
            "E39",
            "T24",
            []
        ],
        [
            "E40",
            "T58",
            []
        ],
        [
            "E41",
            "T60",
            []
        ],
        [
            "E42",
            "T61",
            []
        ]
    ],
    "equivs": [
        [
            "*",
            "OVERLAP",
            "E3",
            "E4",
            "E5",
            "E6",
            "E8"
        ],
        [
            "*",
            "OVERLAP",
            "E7",
            "E9",
            "E10",
            "E13",
            "E14",
            "E15",
            "E16",
            "E17",
            "E19",
            "E20",
            "E21",
            "E22",
            "E23",
            "E24",
            "E25"
        ],
        [
            "*",
            "OVERLAP",
            "E26",
            "E27"
        ],
        [
            "*",
            "OVERLAP",
            "E30",
            "E31",
            "E32",
            "E33",
            "E34"
        ],
        [
            "*",
            "OVERLAP",
            "E35",
            "E36",
            "E37"
        ]
    ],
    "comments": [],
    "text": "CASE: A 28-year-old previously healthy man presented with a 6-week history of palpitations.\nThe symptoms occurred during rest, 2\u20133 times per week, lasted up to 30 minutes at a time and were associated with dyspnea.\nExcept for a grade 2/6 holosystolic tricuspid regurgitation murmur (best heard at the left sternal border with inspiratory accentuation), physical examination yielded unremarkable findings.\nAn electrocardiogram (ECG) revealed normal sinus rhythm and a Wolff\u2013 Parkinson\u2013 White pre-excitation pattern (Fig.1: Top), produced by a right-sided accessory pathway.\nTransthoracic echocardiography demonstrated the presence of Ebstein's anomaly of the tricuspid valve, with apical displacement of the valve and formation of an \u201catrialized\u201d right ventricle (a functional unit between the right atrium and the inlet [inflow] portion of the right ventricle) (Fig.2).\nThe anterior tricuspid valve leaflet was elongated (Fig.2C, arrow), whereas the septal leaflet was rudimentary (Fig.2C, arrowhead).\nContrast echocardiography using saline revealed a patent foramen ovale with right-to-left shunting and bubbles in the left atrium (Fig.2D).\nThe patient underwent an electrophysiologic study with mapping of the accessory pathway, followed by radiofrequency ablation (interruption of the pathway using the heat generated by electromagnetic waves at the tip of an ablation catheter).\nHis post-ablation ECG showed a prolonged PR interval and an odd \u201csecond\u201d QRS complex in leads III, aVF and V2\u2013V4 (Fig.1Bottom), a consequence of abnormal impulse conduction in the \u201catrialized\u201d right ventricle.\nThe patient reported no recurrence of palpitations at follow-up 6 months after the ablation.",
    "action": "getDocument",
    "createdAt": {
        "$date": "2019-03-18T00:46:13.805Z"
    },
    "updatedAt": {
        "$date": "2019-03-18T00:46:13.805Z"
    },
    "__v": 0
} 
        } else {
            reportDetails = {
    "_id": {
        "$oid": "5c8eea55ca49b8479b8938ce"
    },
    "messages": [],
    "source_files": [
        "ann",
        "txt"
    ],
    "modifications": [],
    "normalizations": [],
    "entities": [
        [
            "T1",
            "Age",
            [
                [
                    18,
                    27
                ]
            ]
        ],
        [
            "T2",
            "Sex",
            [
                [
                    28,
                    31
                ]
            ]
        ],
        [
            "T6",
            "Detailed_description",
            [
                [
                    77,
                    84
                ]
            ]
        ],
        [
            "T7",
            "History",
            [
                [
                    101,
                    107
                ]
            ]
        ],
        [
            "T8",
            "History",
            [
                [
                    118,
                    151
                ]
            ]
        ],
        [
            "T10",
            "Biological_structure",
            [
                [
                    129,
                    138
                ]
            ]
        ],
        [
            "T16",
            "Detailed_description",
            [
                [
                    236,
                    240
                ]
            ]
        ],
        [
            "T17",
            "Detailed_description",
            [
                [
                    227,
                    235
                ]
            ]
        ],
        [
            "T18",
            "Biological_structure",
            [
                [
                    252,
                    262
                ]
            ]
        ],
        [
            "T20",
            "Biological_structure",
            [
                [
                    280,
                    284
                ]
            ]
        ],
        [
            "T21",
            "Detailed_description",
            [
                [
                    266,
                    279
                ]
            ]
        ],
        [
            "T22",
            "Biological_structure",
            [
                [
                    311,
                    327
                ]
            ]
        ],
        [
            "T26",
            "Biological_structure",
            [
                [
                    423,
                    429
                ]
            ]
        ],
        [
            "T27",
            "Texture",
            [
                [
                    415,
                    422
                ]
            ]
        ],
        [
            "T28",
            "Detailed_description",
            [
                [
                    401,
                    410
                ]
            ]
        ],
        [
            "T29",
            "Biological_structure",
            [
                [
                    466,
                    488
                ]
            ]
        ],
        [
            "T35",
            "Lab_value",
            [
                [
                    528,
                    536
                ]
            ]
        ],
        [
            "T36",
            "Severity",
            [
                [
                    519,
                    527
                ]
            ]
        ],
        [
            "T37",
            "Biological_attribute",
            [
                [
                    447,
                    452
                ]
            ]
        ],
        [
            "T38",
            "Biological_attribute",
            [
                [
                    453,
                    465
                ]
            ]
        ],
        [
            "T39",
            "Biological_structure",
            [
                [
                    609,
                    620
                ]
            ]
        ],
        [
            "T40",
            "Biological_structure",
            [
                [
                    625,
                    636
                ]
            ]
        ],
        [
            "T42",
            "Biological_structure",
            [
                [
                    592,
                    605
                ]
            ]
        ],
        [
            "T49",
            "Shape",
            [
                [
                    922,
                    932
                ]
            ]
        ],
        [
            "T51",
            "Biological_structure",
            [
                [
                    945,
                    960
                ]
            ]
        ],
        [
            "T52",
            "Biological_structure",
            [
                [
                    1006,
                    1016
                ]
            ]
        ],
        [
            "T53",
            "Detailed_description",
            [
                [
                    981,
                    989
                ]
            ]
        ],
        [
            "T54",
            "Detailed_description",
            [
                [
                    990,
                    994
                ]
            ]
        ],
        [
            "T57",
            "Detailed_description",
            [
                [
                    1028,
                    1034
                ]
            ]
        ],
        [
            "T60",
            "Shape",
            [
                [
                    1139,
                    1149
                ]
            ]
        ],
        [
            "T61",
            "Detailed_description",
            [
                [
                    1150,
                    1170
                ]
            ]
        ],
        [
            "T62",
            "Detailed_description",
            [
                [
                    1171,
                    1180
                ]
            ]
        ],
        [
            "T63",
            "Color",
            [
                [
                    1181,
                    1191
                ]
            ]
        ],
        [
            "T65",
            "Detailed_description",
            [
                [
                    1237,
                    1242
                ]
            ]
        ],
        [
            "T66",
            "Detailed_description",
            [
                [
                    1243,
                    1252
                ]
            ]
        ],
        [
            "T71",
            "Detailed_description",
            [
                [
                    1321,
                    1347
                ]
            ]
        ],
        [
            "T72",
            "Biological_structure",
            [
                [
                    1367,
                    1386
                ]
            ]
        ],
        [
            "T75",
            "Detailed_description",
            [
                [
                    1443,
                    1481
                ]
            ]
        ],
        [
            "T74",
            "Biological_attribute",
            [
                [
                    1392,
                    1410
                ]
            ]
        ],
        [
            "T77",
            "Biological_attribute",
            [
                [
                    1534,
                    1552
                ]
            ]
        ],
        [
            "T78",
            "Detailed_description",
            [
                [
                    1561,
                    1587
                ]
            ]
        ],
        [
            "T79",
            "Biological_structure",
            [
                [
                    1588,
                    1594
                ]
            ]
        ],
        [
            "T80",
            "Biological_attribute",
            [
                [
                    1609,
                    1617
                ]
            ]
        ],
        [
            "T81",
            "Detailed_description",
            [
                [
                    1599,
                    1608
                ]
            ]
        ],
        [
            "T82",
            "Biological_structure",
            [
                [
                    1646,
                    1663
                ]
            ]
        ],
        [
            "T83",
            "Detailed_description",
            [
                [
                    1631,
                    1645
                ]
            ]
        ],
        [
            "T84",
            "Lab_value",
            [
                [
                    1730,
                    1763
                ]
            ]
        ],
        [
            "T85",
            "Biological_structure",
            [
                [
                    1701,
                    1716
                ]
            ]
        ],
        [
            "T86",
            "Detailed_description",
            [
                [
                    1692,
                    1700
                ]
            ]
        ],
        [
            "T87",
            "Detailed_description",
            [
                [
                    1769,
                    1795
                ]
            ]
        ],
        [
            "T89",
            "Detailed_description",
            [
                [
                    1799,
                    1807
                ]
            ]
        ],
        [
            "T90",
            "Detailed_description",
            [
                [
                    1832,
                    1858
                ]
            ]
        ],
        [
            "T92",
            "Severity",
            [
                [
                    1904,
                    1912
                ]
            ]
        ],
        [
            "T93",
            "Lab_value",
            [
                [
                    1913,
                    1921
                ]
            ]
        ],
        [
            "T96",
            "Lab_value",
            [
                [
                    1977,
                    1985
                ]
            ]
        ],
        [
            "T98",
            "Lab_value",
            [
                [
                    2032,
                    2040
                ]
            ]
        ],
        [
            "T99",
            "Detailed_description",
            [
                [
                    2024,
                    2031
                ]
            ]
        ],
        [
            "T101",
            "Lab_value",
            [
                [
                    2073,
                    2081
                ]
            ]
        ],
        [
            "T109",
            "Biological_structure",
            [
                [
                    2228,
                    2237
                ]
            ]
        ],
        [
            "T11",
            "Lab_value",
            [
                [
                    166,
                    183
                ]
            ]
        ]
    ],
    "attributes": [
        [
            "A1",
            "POLARITY",
            "E21",
            "NEG"
        ],
        [
            "A2",
            "POLARITY",
            "E22",
            "NEG"
        ],
        [
            "A3",
            "POLARITY",
            "E29",
            "MAYBE_POS"
        ],
        [
            "A4",
            "TREND",
            "E55",
            "STAY"
        ]
    ],
    "relations": [
        [
            "R1",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T6"
                ],
                [
                    "Arg2",
                    "E3"
                ]
            ]
        ],
        [
            "R2",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T10"
                ],
                [
                    "Arg2",
                    "E4"
                ]
            ]
        ],
        [
            "R5",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T16"
                ],
                [
                    "Arg2",
                    "E9"
                ]
            ]
        ],
        [
            "R6",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T17"
                ],
                [
                    "Arg2",
                    "E9"
                ]
            ]
        ],
        [
            "R7",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T18"
                ],
                [
                    "Arg2",
                    "E9"
                ]
            ]
        ],
        [
            "R8",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T20"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R9",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T21"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R10",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T22"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R11",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E13"
                ],
                [
                    "Arg2",
                    "E12"
                ]
            ]
        ],
        [
            "R12",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T27"
                ],
                [
                    "Arg2",
                    "T26"
                ]
            ]
        ],
        [
            "R13",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T28"
                ],
                [
                    "Arg2",
                    "T26"
                ]
            ]
        ],
        [
            "R15",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T36"
                ],
                [
                    "Arg2",
                    "T35"
                ]
            ]
        ],
        [
            "R16",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T37"
                ],
                [
                    "Arg2",
                    "T38"
                ]
            ]
        ],
        [
            "R17",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T38"
                ],
                [
                    "Arg2",
                    "T29"
                ]
            ]
        ],
        [
            "R18",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E15"
                ],
                [
                    "Arg2",
                    "T35"
                ]
            ]
        ],
        [
            "R19",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E16"
                ],
                [
                    "Arg2",
                    "T35"
                ]
            ]
        ],
        [
            "R20",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E16"
                ],
                [
                    "Arg2",
                    "T35"
                ]
            ]
        ],
        [
            "R21",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E17"
                ],
                [
                    "Arg2",
                    "T35"
                ]
            ]
        ],
        [
            "R22",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E18"
                ],
                [
                    "Arg2",
                    "T35"
                ]
            ]
        ],
        [
            "R23",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E14"
                ],
                [
                    "Arg2",
                    "E15"
                ]
            ]
        ],
        [
            "R24",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E14"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R25",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E14"
                ],
                [
                    "Arg2",
                    "E17"
                ]
            ]
        ],
        [
            "R26",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E14"
                ],
                [
                    "Arg2",
                    "E18"
                ]
            ]
        ],
        [
            "R28",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T42"
                ],
                [
                    "Arg2",
                    "T39"
                ]
            ]
        ],
        [
            "R29",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T42"
                ],
                [
                    "Arg2",
                    "T40"
                ]
            ]
        ],
        [
            "R30",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E19"
                ],
                [
                    "Arg2",
                    "T42"
                ]
            ]
        ],
        [
            "R31",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T49"
                ],
                [
                    "Arg2",
                    "E26"
                ]
            ]
        ],
        [
            "R32",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T51"
                ],
                [
                    "Arg2",
                    "E26"
                ]
            ]
        ],
        [
            "R33",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T52"
                ],
                [
                    "Arg2",
                    "E27"
                ]
            ]
        ],
        [
            "R34",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T54"
                ],
                [
                    "Arg2",
                    "E27"
                ]
            ]
        ],
        [
            "R35",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T53"
                ],
                [
                    "Arg2",
                    "E27"
                ]
            ]
        ],
        [
            "R36",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T57"
                ],
                [
                    "Arg2",
                    "E28"
                ]
            ]
        ],
        [
            "R37",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E33"
                ],
                [
                    "Arg2",
                    "E31"
                ]
            ]
        ],
        [
            "R38",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T66"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ],
        [
            "R39",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T65"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ],
        [
            "R40",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T63"
                ],
                [
                    "Arg2",
                    "E31"
                ]
            ]
        ],
        [
            "R41",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T62"
                ],
                [
                    "Arg2",
                    "E31"
                ]
            ]
        ],
        [
            "R42",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T61"
                ],
                [
                    "Arg2",
                    "E31"
                ]
            ]
        ],
        [
            "R43",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T60"
                ],
                [
                    "Arg2",
                    "E31"
                ]
            ]
        ],
        [
            "R45",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T71"
                ],
                [
                    "Arg2",
                    "E35"
                ]
            ]
        ],
        [
            "R46",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T72"
                ],
                [
                    "Arg2",
                    "E35"
                ]
            ]
        ],
        [
            "R49",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T74"
                ],
                [
                    "Arg2",
                    "E36"
                ]
            ]
        ],
        [
            "R50",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T75"
                ],
                [
                    "Arg2",
                    "T74"
                ]
            ]
        ],
        [
            "R51",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T81"
                ],
                [
                    "Arg2",
                    "T80"
                ]
            ]
        ],
        [
            "R52",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T78"
                ],
                [
                    "Arg2",
                    "T79"
                ]
            ]
        ],
        [
            "R53",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T83"
                ],
                [
                    "Arg2",
                    "T82"
                ]
            ]
        ],
        [
            "R54",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T77"
                ],
                [
                    "Arg2",
                    "E38"
                ]
            ]
        ],
        [
            "R55",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T79"
                ],
                [
                    "Arg2",
                    "T77"
                ]
            ]
        ],
        [
            "R56",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T80"
                ],
                [
                    "Arg2",
                    "T77"
                ]
            ]
        ],
        [
            "R57",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T82"
                ],
                [
                    "Arg2",
                    "T77"
                ]
            ]
        ],
        [
            "R58",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T86"
                ],
                [
                    "Arg2",
                    "T85"
                ]
            ]
        ],
        [
            "R59",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T84"
                ],
                [
                    "Arg2",
                    "T85"
                ]
            ]
        ],
        [
            "R60",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T87"
                ],
                [
                    "Arg2",
                    "T85"
                ]
            ]
        ],
        [
            "R61",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T90"
                ],
                [
                    "Arg2",
                    "E37"
                ]
            ]
        ],
        [
            "R62",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T89"
                ],
                [
                    "Arg2",
                    "E37"
                ]
            ]
        ],
        [
            "R63",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E40"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R64",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E41"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R65",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E42"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R66",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T99"
                ],
                [
                    "Arg2",
                    "T98"
                ]
            ]
        ],
        [
            "R67",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E43"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R68",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E44"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R69",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E45"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R70",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E46"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R71",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E47"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R72",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E48"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R73",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T92"
                ],
                [
                    "Arg2",
                    "T93"
                ]
            ]
        ],
        [
            "R74",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E40"
                ],
                [
                    "Arg2",
                    "T93"
                ]
            ]
        ],
        [
            "R75",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E41"
                ],
                [
                    "Arg2",
                    "T93"
                ]
            ]
        ],
        [
            "R76",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E42"
                ],
                [
                    "Arg2",
                    "T96"
                ]
            ]
        ],
        [
            "R77",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E43"
                ],
                [
                    "Arg2",
                    "T98"
                ]
            ]
        ],
        [
            "R78",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E44"
                ],
                [
                    "Arg2",
                    "T101"
                ]
            ]
        ],
        [
            "R79",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E45"
                ],
                [
                    "Arg2",
                    "T101"
                ]
            ]
        ],
        [
            "R80",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E46"
                ],
                [
                    "Arg2",
                    "T101"
                ]
            ]
        ],
        [
            "R81",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E47"
                ],
                [
                    "Arg2",
                    "T101"
                ]
            ]
        ],
        [
            "R82",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E48"
                ],
                [
                    "Arg2",
                    "T101"
                ]
            ]
        ],
        [
            "R83",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E50"
                ],
                [
                    "Arg2",
                    "E49"
                ]
            ]
        ],
        [
            "R85",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E53"
                ],
                [
                    "Arg2",
                    "E30"
                ]
            ]
        ],
        [
            "R14",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E14"
                ],
                [
                    "Arg2",
                    "E13"
                ]
            ]
        ],
        [
            "R27",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E19"
                ],
                [
                    "Arg2",
                    "E14"
                ]
            ]
        ],
        [
            "R44",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E35"
                ],
                [
                    "Arg2",
                    "E33"
                ]
            ]
        ],
        [
            "R47",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E36"
                ],
                [
                    "Arg2",
                    "E35"
                ]
            ]
        ],
        [
            "R48",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E38"
                ],
                [
                    "Arg2",
                    "E36"
                ]
            ]
        ],
        [
            "R3",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T11"
                ],
                [
                    "Arg2",
                    "E4"
                ]
            ]
        ],
        [
            "R4",
            "AFTER",
            [
                [
                    "Arg1",
                    "E3"
                ],
                [
                    "Arg2",
                    "E4"
                ]
            ]
        ],
        [
            "R84",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E4"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R86",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E8"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R87",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E9"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R88",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E18"
                ],
                [
                    "Arg2",
                    "E20"
                ]
            ]
        ],
        [
            "R89",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E21"
                ],
                [
                    "Arg2",
                    "E22"
                ]
            ]
        ],
        [
            "R90",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E22"
                ],
                [
                    "Arg2",
                    "E23"
                ]
            ]
        ],
        [
            "R91",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E24"
                ],
                [
                    "Arg2",
                    "E25"
                ]
            ]
        ],
        [
            "R92",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E27"
                ],
                [
                    "Arg2",
                    "E28"
                ]
            ]
        ],
        [
            "R93",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T109"
                ],
                [
                    "Arg2",
                    "E51"
                ]
            ]
        ],
        [
            "R94",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E51"
                ],
                [
                    "Arg2",
                    "E50"
                ]
            ]
        ],
        [
            "R95",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E50"
                ],
                [
                    "Arg2",
                    "E52"
                ]
            ]
        ]
    ],
    "triggers": [
        [
            "T3",
            "Clinical_event",
            [
                [
                    36,
                    45
                ]
            ]
        ],
        [
            "T4",
            "Sign_symptom",
            [
                [
                    65,
                    70
                ]
            ]
        ],
        [
            "T5",
            "Sign_symptom",
            [
                [
                    85,
                    90
                ]
            ]
        ],
        [
            "T9",
            "Disease_disorder",
            [
                [
                    139,
                    151
                ]
            ]
        ],
        [
            "T13",
            "Diagnostic_procedure",
            [
                [
                    187,
                    207
                ]
            ]
        ],
        [
            "T14",
            "Diagnostic_procedure",
            [
                [
                    208,
                    212
                ]
            ]
        ],
        [
            "T15",
            "Sign_symptom",
            [
                [
                    241,
                    248
                ]
            ]
        ],
        [
            "T19",
            "Diagnostic_procedure",
            [
                [
                    285,
                    291
                ]
            ]
        ],
        [
            "T23",
            "Diagnostic_procedure",
            [
                [
                    333,
                    356
                ]
            ]
        ],
        [
            "T24",
            "Sign_symptom",
            [
                [
                    376,
                    379
                ]
            ]
        ],
        [
            "T25",
            "Coreference",
            [
                [
                    385,
                    396
                ]
            ]
        ],
        [
            "T30",
            "Coreference",
            [
                [
                    502,
                    513
                ]
            ]
        ],
        [
            "T31",
            "Diagnostic_procedure",
            [
                [
                    541,
                    554
                ]
            ]
        ],
        [
            "T32",
            "Diagnostic_procedure",
            [
                [
                    556,
                    564
                ]
            ]
        ],
        [
            "T33",
            "Diagnostic_procedure",
            [
                [
                    566,
                    570
                ]
            ]
        ],
        [
            "T34",
            "Diagnostic_procedure",
            [
                [
                    575,
                    579
                ]
            ]
        ],
        [
            "T41",
            "Coreference",
            [
                [
                    648,
                    659
                ]
            ]
        ],
        [
            "T43",
            "Diagnostic_procedure",
            [
                [
                    688,
                    711
                ]
            ]
        ],
        [
            "T44",
            "Sign_symptom",
            [
                [
                    713,
                    756
                ]
            ]
        ],
        [
            "T45",
            "Activity",
            [
                [
                    761,
                    773
                ]
            ]
        ],
        [
            "T46",
            "Sign_symptom",
            [
                [
                    827,
                    831
                ]
            ]
        ],
        [
            "T47",
            "Duration",
            [
                [
                    832,
                    858
                ]
            ]
        ],
        [
            "T48",
            "Diagnostic_procedure",
            [
                [
                    884,
                    891
                ]
            ]
        ],
        [
            "T50",
            "Sign_symptom",
            [
                [
                    933,
                    937
                ]
            ]
        ],
        [
            "T55",
            "Sign_symptom",
            [
                [
                    995,
                    1002
                ]
            ]
        ],
        [
            "T56",
            "Diagnostic_procedure",
            [
                [
                    1035,
                    1041
                ]
            ]
        ],
        [
            "T58",
            "Sign_symptom",
            [
                [
                    1064,
                    1088
                ]
            ]
        ],
        [
            "T59",
            "Therapeutic_procedure",
            [
                [
                    1103,
                    1112
                ]
            ]
        ],
        [
            "T64",
            "Sign_symptom",
            [
                [
                    1192,
                    1196
                ]
            ]
        ],
        [
            "T67",
            "Sign_symptom",
            [
                [
                    1253,
                    1260
                ]
            ]
        ],
        [
            "T68",
            "Coreference",
            [
                [
                    1272,
                    1281
                ]
            ]
        ],
        [
            "T69",
            "Diagnostic_procedure",
            [
                [
                    1283,
                    1298
                ]
            ]
        ],
        [
            "T70",
            "Coreference",
            [
                [
                    1304,
                    1315
                ]
            ]
        ],
        [
            "T73",
            "Coreference",
            [
                [
                    1426,
                    1437
                ]
            ]
        ],
        [
            "T76",
            "Coreference",
            [
                [
                    1497,
                    1508
                ]
            ]
        ],
        [
            "T88",
            "Sign_symptom",
            [
                [
                    1811,
                    1822
                ]
            ]
        ],
        [
            "T91",
            "Diagnostic_procedure",
            [
                [
                    1860,
                    1881
                ]
            ]
        ],
        [
            "T94",
            "Diagnostic_procedure",
            [
                [
                    1926,
                    1939
                ]
            ]
        ],
        [
            "T95",
            "Diagnostic_procedure",
            [
                [
                    1952,
                    1960
                ]
            ]
        ],
        [
            "T97",
            "Diagnostic_procedure",
            [
                [
                    1990,
                    1994
                ]
            ]
        ],
        [
            "T100",
            "Diagnostic_procedure",
            [
                [
                    2045,
                    2049
                ]
            ]
        ],
        [
            "T102",
            "Diagnostic_procedure",
            [
                [
                    2086,
                    2097
                ]
            ]
        ],
        [
            "T103",
            "Diagnostic_procedure",
            [
                [
                    2099,
                    2126
                ]
            ]
        ],
        [
            "T104",
            "Diagnostic_procedure",
            [
                [
                    2128,
                    2131
                ]
            ]
        ],
        [
            "T105",
            "Diagnostic_procedure",
            [
                [
                    2133,
                    2137
                ]
            ]
        ],
        [
            "T106",
            "Diagnostic_procedure",
            [
                [
                    2142,
                    2147
                ]
            ]
        ],
        [
            "T107",
            "Sign_symptom",
            [
                [
                    2178,
                    2220
                ]
            ]
        ],
        [
            "T108",
            "Diagnostic_procedure",
            [
                [
                    2153,
                    2177
                ]
            ]
        ],
        [
            "T110",
            "Sign_symptom",
            [
                [
                    2245,
                    2256
                ]
            ]
        ],
        [
            "T111",
            "Date",
            [
                [
                    2266,
                    2283
                ]
            ]
        ],
        [
            "T112",
            "Coreference",
            [
                [
                    2284,
                    2293
                ]
            ]
        ],
        [
            "T113",
            "Outcome",
            [
                [
                    2310,
                    2320
                ]
            ]
        ],
        [
            "T114",
            "Sign_symptom",
            [
                [
                    2326,
                    2374
                ]
            ]
        ]
    ],
    "events": [
        [
            "E1",
            "T3",
            []
        ],
        [
            "E2",
            "T4",
            []
        ],
        [
            "E3",
            "T5",
            []
        ],
        [
            "E4",
            "T9",
            []
        ],
        [
            "E7",
            "T13",
            []
        ],
        [
            "E8",
            "T14",
            []
        ],
        [
            "E9",
            "T15",
            []
        ],
        [
            "E10",
            "T19",
            []
        ],
        [
            "E11",
            "T23",
            []
        ],
        [
            "E12",
            "T24",
            []
        ],
        [
            "E13",
            "T25",
            []
        ],
        [
            "E14",
            "T30",
            []
        ],
        [
            "E15",
            "T31",
            []
        ],
        [
            "E16",
            "T32",
            []
        ],
        [
            "E17",
            "T33",
            []
        ],
        [
            "E18",
            "T34",
            []
        ],
        [
            "E19",
            "T41",
            []
        ],
        [
            "E20",
            "T43",
            []
        ],
        [
            "E21",
            "T44",
            []
        ],
        [
            "E22",
            "T45",
            []
        ],
        [
            "E23",
            "T46",
            []
        ],
        [
            "E24",
            "T47",
            []
        ],
        [
            "E25",
            "T48",
            []
        ],
        [
            "E26",
            "T50",
            []
        ],
        [
            "E27",
            "T55",
            []
        ],
        [
            "E28",
            "T56",
            []
        ],
        [
            "E29",
            "T58",
            []
        ],
        [
            "E30",
            "T59",
            []
        ],
        [
            "E31",
            "T64",
            []
        ],
        [
            "E32",
            "T67",
            []
        ],
        [
            "E33",
            "T68",
            []
        ],
        [
            "E34",
            "T69",
            []
        ],
        [
            "E35",
            "T70",
            []
        ],
        [
            "E36",
            "T73",
            []
        ],
        [
            "E38",
            "T76",
            []
        ],
        [
            "E37",
            "T88",
            []
        ],
        [
            "E39",
            "T91",
            []
        ],
        [
            "E40",
            "T94",
            []
        ],
        [
            "E41",
            "T95",
            []
        ],
        [
            "E42",
            "T97",
            []
        ],
        [
            "E43",
            "T100",
            []
        ],
        [
            "E44",
            "T102",
            []
        ],
        [
            "E45",
            "T103",
            []
        ],
        [
            "E46",
            "T104",
            []
        ],
        [
            "E47",
            "T105",
            []
        ],
        [
            "E48",
            "T106",
            []
        ],
        [
            "E49",
            "T107",
            []
        ],
        [
            "E50",
            "T108",
            []
        ],
        [
            "E51",
            "T110",
            []
        ],
        [
            "E52",
            "T111",
            []
        ],
        [
            "E53",
            "T112",
            []
        ],
        [
            "E54",
            "T113",
            []
        ],
        [
            "E55",
            "T114",
            []
        ]
    ],
    "equivs": [
        [
            "*",
            "OVERLAP",
            "E1",
            "E2",
            "E3"
        ],
        [
            "*",
            "OVERLAP",
            "E7",
            "E9"
        ],
        [
            "*",
            "OVERLAP",
            "E10",
            "E11",
            "E12",
            "E15",
            "E16",
            "E17",
            "E18"
        ],
        [
            "*",
            "OVERLAP",
            "E20",
            "E21"
        ],
        [
            "*",
            "OVERLAP",
            "E23",
            "E24"
        ],
        [
            "*",
            "OVERLAP",
            "E25",
            "E26",
            "E27"
        ],
        [
            "*",
            "OVERLAP",
            "E28",
            "E29",
            "E30",
            "E31",
            "E32",
            "E34",
            "E37",
            "E39",
            "E50"
        ],
        [
            "*",
            "OVERLAP",
            "E52",
            "E54",
            "E55"
        ]
    ],
    "comments": [
        [
            "E12",
            "AnnotatorNotes",
            "Langerhans cell histiocytosis"
        ],
        [
            "E15",
            "AnnotatorNotes",
            "This is a Diagnostic Procedure because a test had to be run to detect presence of this protein."
        ],
        [
            "E22",
            "AnnotatorNotes",
            "Note that this is an activity here though it was history before."
        ],
        [
            "E52",
            "AnnotatorNotes",
            "Note that this is a date due to the \"after\" (not a duration, as those are continuous)"
        ]
    ],
    "text": "The patient was a 34-yr-old man who presented with complaints of fever and a chronic cough.\nHe was a smoker and had a history of pulmonary tuberculosis that had been treated and cured.\nA computed tomographic (CT) scan revealed multiple tiny nodules in both lungs.\nA thoracoscopic lung biopsy was taken from the right upper lobe.\nThe microscopic examination revealed a typical LCH.\nThe tumor cells had vesicular and grooved nuclei, and they formed small aggregations around the bronchioles (Fig.1).\nThe tumor cells were strongly positive for S-100 protein, vimentin, CD68 and CD1a.\nThere were infiltrations of lymphocytes and eosinophils around the tumor cells.\nWith performing additional radiologic examinations, no other organs were thought to be involved.\nHe quit smoking, but he received no other specific treatment.\nHe was well for the following one year.\nAfter this, a follow-up CT scan was performed and it showed a 4 cm-sized mass in the left lower lobe, in addition to the multiple tiny nodules in both lungs (Fig.2).\nA needle biopsy specimen revealed the possibility of a sarcoma; therefore, a lobectomy was performed.\nGrossly, a 4 cm-sized poorly-circumscribed lobulated gray-white mass was found (Fig.3), and there were a few small satellite nodules around the main mass.\nMicroscopically, the tumor cells were aggregated in large sheets and they showed an infiltrative growth.\nThe cytologic features of some of the tumor cells were similar to those seen in a typical LCH.\nHowever, many tumor cells showed overtly malignant cytologic features such as pleomorphic/hyperchromatic nuclei and prominent nucleoli (Fig.4), and multinucleated tumor giant cells were also found.\nThere were numerous mitotic figures ranging from 30 to 60 per 10 high power fields, and some of them were abnormal.\nA few foci of typical LCH remained around the main tumor mass.\nImmunohistochemically, the tumor cells were strongly positive for S-100 protein (Fig.5) and vimentin; they were also positive for CD68 (Dako N1577, Clone KPI), and focally positive for CD1a (Fig.6), and they were negative for cytokeratin, epithelial membrane antigen, CD3, CD20 and HMB45.\nThe ultrastructural analysis failed to demonstrate any Birbeck granules in the cytoplasm of the tumor cells.\nNow, at five months after lobectomy, the patient is doing well with no significant change in the radiologic findings.",
    "action": "getDocument",
    "createdAt": {
        "$date": "2019-03-18T00:46:14.006Z"
    },
    "updatedAt": {
        "$date": "2019-03-18T00:46:14.006Z"
    },
    "__v": 0
}
        }

        console.log(11111111);
        return res.json(reportDetails)
    });

    // putCaseReport
    router.post("/putCaseReport", (req, res) => {
        const {txt, ann} = req.body;
        let caseReport = new CaseReport();

        console.log('caseReport api messge');

        caseReport.text = txt;
        caseReport.entities = [];
        caseReport.attributes = [];
        caseReport.relations = [];
        caseReport.triggers = [];
        caseReport.events = [];
        caseReport.comments = [];
        caseReport.equivs = [];
        caseReport.action = "getDocument";
        caseReport.source_files = ["ann", "txt"];

        if (typeof req.body.ann == 'undefined') {
            return res.json({success: false, error: "ann input is not defined"});
        }

        let lines = ann.split(/\r?\n/);
        var i;
        for (i = 0; i<lines.length; i++) {
            let line = lines[i];
            let infos = line.split('\t');
            var type = infos[0];

            // entity or trigger-event
            if (type.charAt(0) == 'T') {            
                // if not followed by event, then this is entity
                if (i==lines.length-1 || lines[i+1].charAt(0)!= 'E') {
                    // add entity to caseReport.entities
                    let entityID = infos[0];
                    let entityContent = infos[1].split(' ');
                    caseReport.entities.push([entityID, entityContent[0], [[parseInt(entityContent[1]), parseInt(entityContent[2])]]]);
                }
                // else this is trigger for event
                else {
                    // add trigger to caseReport.entities
                    let triggerID = infos[0];
                    let triggerContent = infos[1].split(' ');
                    caseReport.triggers.push([triggerID, triggerContent[0], [[parseInt(triggerContent[1]), parseInt(triggerContent[2])]]]);
                }
            } 
            // relation
            else if (type.charAt(0) == 'R') {     
                let relationID = infos[0];
                let relationContent = infos[1].split(' ');
                caseReport.relations.push([relationID, relationContent[0], [["Arg1",relationContent[1].split(':')[1]], ["Arg2", relationContent[2].split(':')[1]]]]);
            } 
            // event
            else if (type.charAt(0) == 'E') {     
                // add to caseReports.events
                let eventID = infos[0];
                caseReport.events.push([eventID, infos[1].split(':')[1].trim(), []]);

            } 
            // attribute
            else if (type.charAt(0) == 'A') {     
                let attributeID = infos[0];
                let attirbuteContent = infos[1].split(' ');
                caseReport.attributes.push([attributeID, attirbuteContent[0], attirbuteContent[1], attirbuteContent[2]]);
            }
            // comment
            else if (type.charAt(0) == '#') {
                let commentContent = infos[1].split(' ');
                caseReport.comments.push([commentContent[1], commentContent[0], infos[2]]);
            }
            // overlap
            else if (type.charAt(0) == '*') {
                let overlapContent = infos[1].split(' ');
                let overlapData = [];
                overlapData.push('*');
                var j;
                for (j =0; j<overlapContent.length; j++) {
                    overlapData.push(overlapContent[j]);
                }
                caseReport.equivs.push(overlapData);
            }
        }

        caseReport.save(err => {
            if (err) return res.json({ success: false, error: err });
            return res.json({ success: true});
        });
    });

    // For Future Use If We Are Having Users
    /* --------------------------------------- SIGNUP --------------------------------------- */

    // app.get('/signup', function(req, res) {
    //     res.render('home/signup', {
    //         loggedIn : req.loggedIn,
    //         user : req.user, 
    //         message: req.flash('signupMessage') });
    // });

    /* --------------------------------------- LOGOUT --------------------------------------- */

    // app.get('/logout', function(req, res) {
    //     req.logout();
    //     res.redirect('/home/login');
    // });
};