import React, { Component } from "react";
import Cytoscape from 'cytoscape';
import CytoscapeComponent from 'react-cytoscapejs';
import Dagre from 'cytoscape-dagre';
import {buildGraphElementsFromGraphData} from '../../utils';

Cytoscape.use(Dagre);



class Graph extends Component {

  render(){
    const graphData  = {
    "_id": {
        "$oid": "5cb4c52515ca6da78e3afd99"
    },
    "messages": [],
    "source_files": [
        "ann",
        "txt"
    ],
    "modifications": [],
    "normalizations": [],
    "entities": [
        [
            "T1",
            "Age",
            [
                [
                    2,
                    13
                ]
            ]
        ],
        [
            "T2",
            "Sex",
            [
                [
                    14,
                    17
                ]
            ]
        ],
        [
            "T4",
            "History",
            [
                [
                    25,
                    61
                ]
            ]
        ],
        [
            "T6",
            "Nonbiological_location",
            [
                [
                    74,
                    82
                ]
            ]
        ],
        [
            "T9",
            "Detailed_description",
            [
                [
                    107,
                    115
                ]
            ]
        ],
        [
            "T10",
            "Biological_structure",
            [
                [
                    116,
                    121
                ]
            ]
        ],
        [
            "T12",
            "History",
            [
                [
                    142,
                    185
                ]
            ]
        ],
        [
            "T18",
            "Detailed_description",
            [
                [
                    296,
                    300
                ]
            ]
        ],
        [
            "T19",
            "Biological_structure",
            [
                [
                    313,
                    328
                ]
            ]
        ],
        [
            "T20",
            "Distance",
            [
                [
                    344,
                    351
                ]
            ]
        ],
        [
            "T21",
            "Biological_structure",
            [
                [
                    399,
                    409
                ]
            ]
        ],
        [
            "T22",
            "Biological_structure",
            [
                [
                    414,
                    425
                ]
            ]
        ],
        [
            "T24",
            "Biological_structure",
            [
                [
                    441,
                    455
                ]
            ]
        ],
        [
            "T25",
            "Biological_structure",
            [
                [
                    482,
                    497
                ]
            ]
        ],
        [
            "T27",
            "Detailed_description",
            [
                [
                    523,
                    532
                ]
            ]
        ],
        [
            "T29",
            "Biological_structure",
            [
                [
                    547,
                    552
                ]
            ]
        ],
        [
            "T30",
            "Detailed_description",
            [
                [
                    538,
                    546
                ]
            ]
        ],
        [
            "T31",
            "Distance",
            [
                [
                    573,
                    586
                ]
            ]
        ],
        [
            "T33",
            "Biological_structure",
            [
                [
                    629,
                    634
                ]
            ]
        ],
        [
            "T34",
            "Detailed_description",
            [
                [
                    651,
                    672
                ]
            ]
        ],
        [
            "T35",
            "Detailed_description",
            [
                [
                    617,
                    621
                ]
            ]
        ],
        [
            "T37",
            "Biological_structure",
            [
                [
                    682,
                    695
                ]
            ]
        ],
        [
            "T38",
            "Detailed_description",
            [
                [
                    700,
                    711
                ]
            ]
        ],
        [
            "T47",
            "Lab_value",
            [
                [
                    787,
                    797
                ]
            ]
        ],
        [
            "T48",
            "Lab_value",
            [
                [
                    810,
                    819
                ]
            ]
        ],
        [
            "T49",
            "Lab_value",
            [
                [
                    836,
                    847
                ]
            ]
        ],
        [
            "T50",
            "Lab_value",
            [
                [
                    872,
                    879
                ]
            ]
        ],
        [
            "T51",
            "Lab_value",
            [
                [
                    902,
                    909
                ]
            ]
        ],
        [
            "T52",
            "Lab_value",
            [
                [
                    943,
                    951
                ]
            ]
        ],
        [
            "T59",
            "Detailed_description",
            [
                [
                    1236,
                    1245
                ]
            ]
        ],
        [
            "T61",
            "Dosage",
            [
                [
                    1284,
                    1310
                ]
            ]
        ],
        [
            "T64",
            "Dosage",
            [
                [
                    1336,
                    1363
                ]
            ]
        ],
        [
            "T71",
            "Biological_structure",
            [
                [
                    1527,
                    1536
                ]
            ]
        ],
        [
            "T74",
            "Lab_value",
            [
                [
                    1589,
                    1609
                ]
            ]
        ],
        [
            "T76",
            "Lab_value",
            [
                [
                    1628,
                    1638
                ]
            ]
        ],
        [
            "T79",
            "Severity",
            [
                [
                    1676,
                    1682
                ]
            ]
        ],
        [
            "T81",
            "Lab_value",
            [
                [
                    1702,
                    1710
                ]
            ]
        ],
        [
            "T82",
            "Lab_value",
            [
                [
                    1734,
                    1741
                ]
            ]
        ],
        [
            "T84",
            "Lab_value",
            [
                [
                    1747,
                    1756
                ]
            ]
        ],
        [
            "T86",
            "Biological_structure",
            [
                [
                    1817,
                    1833
                ]
            ]
        ],
        [
            "T89",
            "Detailed_description",
            [
                [
                    1885,
                    1890
                ]
            ]
        ],
        [
            "T91",
            "Biological_structure",
            [
                [
                    1908,
                    1913
                ]
            ]
        ],
        [
            "T92",
            "Biological_structure",
            [
                [
                    1927,
                    1936
                ]
            ]
        ],
        [
            "T94",
            "Detailed_description",
            [
                [
                    1954,
                    1961
                ]
            ]
        ],
        [
            "T97",
            "Detailed_description",
            [
                [
                    2044,
                    2069
                ]
            ]
        ],
        [
            "T99",
            "Biological_structure",
            [
                [
                    2097,
                    2102
                ]
            ]
        ],
        [
            "T100",
            "Detailed_description",
            [
                [
                    2088,
                    2096
                ]
            ]
        ],
        [
            "T102",
            "Detailed_description",
            [
                [
                    2129,
                    2140
                ]
            ]
        ],
        [
            "T104",
            "Detailed_description",
            [
                [
                    2171,
                    2188
                ]
            ]
        ],
        [
            "T107",
            "Biological_structure",
            [
                [
                    2263,
                    2294
                ]
            ]
        ],
        [
            "T110",
            "Detailed_description",
            [
                [
                    2317,
                    2324
                ]
            ]
        ],
        [
            "T111",
            "Biological_structure",
            [
                [
                    2346,
                    2363
                ]
            ]
        ],
        [
            "T114",
            "Biological_structure",
            [
                [
                    2695,
                    2719
                ]
            ]
        ],
        [
            "T118",
            "Lab_value",
            [
                [
                    2816,
                    2822
                ]
            ]
        ],
        [
            "T119",
            "Biological_structure",
            [
                [
                    2841,
                    2860
                ]
            ]
        ],
        [
            "T122",
            "Administration",
            [
                [
                    2998,
                    3010
                ]
            ]
        ],
        [
            "T123",
            "Dosage",
            [
                [
                    3014,
                    3017
                ]
            ]
        ],
        [
            "T125",
            "Lab_value",
            [
                [
                    3063,
                    3073
                ]
            ]
        ],
        [
            "T127",
            "Lab_value",
            [
                [
                    3110,
                    3121
                ]
            ]
        ],
        [
            "T131",
            "Biological_structure",
            [
                [
                    3222,
                    3227
                ]
            ]
        ],
        [
            "T134",
            "Lab_value",
            [
                [
                    3298,
                    3313
                ]
            ]
        ],
        [
            "T136",
            "Detailed_description",
            [
                [
                    3340,
                    3349
                ]
            ]
        ],
        [
            "T137",
            "Dosage",
            [
                [
                    3408,
                    3419
                ]
            ]
        ],
        [
            "T139",
            "Lab_value",
            [
                [
                    3423,
                    3427
                ]
            ]
        ],
        [
            "T140",
            "Lab_value",
            [
                [
                    3428,
                    3435
                ]
            ]
        ],
        [
            "T143",
            "Biological_structure",
            [
                [
                    3488,
                    3492
                ]
            ]
        ],
        [
            "T144",
            "Biological_structure",
            [
                [
                    3497,
                    3502
                ]
            ]
        ]
    ],
    "attributes": [
        [
            "A1",
            "POLARITY",
            "E6",
            "NEG"
        ],
        [
            "A2",
            "POLARITY",
            "E7",
            "NEG"
        ],
        [
            "A3",
            "POLARITY",
            "E24",
            "NEG"
        ],
        [
            "A4",
            "POLARITY",
            "E53",
            "UNCERTAIN"
        ],
        [
            "A5",
            "POLARITY",
            "E56",
            "NEG"
        ],
        [
            "A6",
            "POLARITY",
            "E58",
            "NEG"
        ],
        [
            "A7",
            "POLARITY",
            "E69",
            "NEG"
        ],
        [
            "A8",
            "TREND",
            "E70",
            "DEC"
        ],
        [
            "A9",
            "POLARITY",
            "E71",
            "NEG"
        ]
    ],
    "relations": [
        [
            "R1",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T6"
                ],
                [
                    "Arg2",
                    "E2"
                ]
            ]
        ],
        [
            "R2",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T10"
                ],
                [
                    "Arg2",
                    "E3"
                ]
            ]
        ],
        [
            "R3",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T9"
                ],
                [
                    "Arg2",
                    "E3"
                ]
            ]
        ],
        [
            "R4",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E5"
                ],
                [
                    "Arg2",
                    "E1"
                ]
            ]
        ],
        [
            "R5",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E9"
                ],
                [
                    "Arg2",
                    "E8"
                ]
            ]
        ],
        [
            "R6",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T18"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R7",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T19"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R8",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T20"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R9",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T21"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R10",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T22"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R11",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T24"
                ],
                [
                    "Arg2",
                    "E11"
                ]
            ]
        ],
        [
            "R12",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T25"
                ],
                [
                    "Arg2",
                    "E11"
                ]
            ]
        ],
        [
            "R13",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T27"
                ],
                [
                    "Arg2",
                    "E12"
                ]
            ]
        ],
        [
            "R14",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T29"
                ],
                [
                    "Arg2",
                    "E13"
                ]
            ]
        ],
        [
            "R15",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T30"
                ],
                [
                    "Arg2",
                    "E13"
                ]
            ]
        ],
        [
            "R16",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T31"
                ],
                [
                    "Arg2",
                    "E13"
                ]
            ]
        ],
        [
            "R17",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E14"
                ],
                [
                    "Arg2",
                    "E13"
                ]
            ]
        ],
        [
            "R18",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T33"
                ],
                [
                    "Arg2",
                    "E14"
                ]
            ]
        ],
        [
            "R19",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T34"
                ],
                [
                    "Arg2",
                    "E14"
                ]
            ]
        ],
        [
            "R20",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T35"
                ],
                [
                    "Arg2",
                    "E14"
                ]
            ]
        ],
        [
            "R21",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T37"
                ],
                [
                    "Arg2",
                    "E15"
                ]
            ]
        ],
        [
            "R22",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T38"
                ],
                [
                    "Arg2",
                    "E15"
                ]
            ]
        ],
        [
            "R23",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E23"
                ],
                [
                    "Arg2",
                    "E22"
                ]
            ]
        ],
        [
            "R24",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T47"
                ],
                [
                    "Arg2",
                    "E17"
                ]
            ]
        ],
        [
            "R25",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T48"
                ],
                [
                    "Arg2",
                    "E18"
                ]
            ]
        ],
        [
            "R26",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T49"
                ],
                [
                    "Arg2",
                    "E19"
                ]
            ]
        ],
        [
            "R27",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T50"
                ],
                [
                    "Arg2",
                    "E20"
                ]
            ]
        ],
        [
            "R28",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T51"
                ],
                [
                    "Arg2",
                    "E21"
                ]
            ]
        ],
        [
            "R29",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T52"
                ],
                [
                    "Arg2",
                    "E22"
                ]
            ]
        ],
        [
            "R30",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E17"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R31",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E18"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R32",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E19"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R33",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E20"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R34",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E21"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R35",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E22"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R36",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E28"
                ],
                [
                    "Arg2",
                    "E25"
                ]
            ]
        ],
        [
            "R37",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T59"
                ],
                [
                    "Arg2",
                    "E29"
                ]
            ]
        ],
        [
            "R38",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T64"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ],
        [
            "R39",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T61"
                ],
                [
                    "Arg2",
                    "E30"
                ]
            ]
        ],
        [
            "R40",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E30"
                ],
                [
                    "Arg2",
                    "E29"
                ]
            ]
        ],
        [
            "R41",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E32"
                ],
                [
                    "Arg2",
                    "E29"
                ]
            ]
        ],
        [
            "R42",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T71"
                ],
                [
                    "Arg2",
                    "E38"
                ]
            ]
        ],
        [
            "R43",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T74"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R44",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T76"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R45",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T79"
                ],
                [
                    "Arg2",
                    "E43"
                ]
            ]
        ],
        [
            "R46",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E44"
                ],
                [
                    "Arg2",
                    "E42"
                ]
            ]
        ],
        [
            "R47",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T81"
                ],
                [
                    "Arg2",
                    "E44"
                ]
            ]
        ],
        [
            "R48",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T82"
                ],
                [
                    "Arg2",
                    "E44"
                ]
            ]
        ],
        [
            "R49",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T84"
                ],
                [
                    "Arg2",
                    "E44"
                ]
            ]
        ],
        [
            "R50",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T86"
                ],
                [
                    "Arg2",
                    "E46"
                ]
            ]
        ],
        [
            "R51",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T89"
                ],
                [
                    "Arg2",
                    "E48"
                ]
            ]
        ],
        [
            "R52",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T91"
                ],
                [
                    "Arg2",
                    "E49"
                ]
            ]
        ],
        [
            "R53",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E49"
                ],
                [
                    "Arg2",
                    "E48"
                ]
            ]
        ],
        [
            "R54",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T92"
                ],
                [
                    "Arg2",
                    "E49"
                ]
            ]
        ],
        [
            "R55",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T94"
                ],
                [
                    "Arg2",
                    "E50"
                ]
            ]
        ],
        [
            "R56",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E51"
                ],
                [
                    "Arg2",
                    "E47"
                ]
            ]
        ],
        [
            "R57",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T97"
                ],
                [
                    "Arg2",
                    "E52"
                ]
            ]
        ],
        [
            "R58",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T100"
                ],
                [
                    "Arg2",
                    "E53"
                ]
            ]
        ],
        [
            "R59",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T99"
                ],
                [
                    "Arg2",
                    "E53"
                ]
            ]
        ],
        [
            "R60",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T102"
                ],
                [
                    "Arg2",
                    "E54"
                ]
            ]
        ],
        [
            "R61",
            "CAUSE",
            [
                [
                    "Arg1",
                    "E53"
                ],
                [
                    "Arg2",
                    "E54"
                ]
            ]
        ],
        [
            "R62",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T104"
                ],
                [
                    "Arg2",
                    "E55"
                ]
            ]
        ],
        [
            "R63",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T107"
                ],
                [
                    "Arg2",
                    "E57"
                ]
            ]
        ],
        [
            "R64",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T110"
                ],
                [
                    "Arg2",
                    "E59"
                ]
            ]
        ],
        [
            "R65",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T111"
                ],
                [
                    "Arg2",
                    "E59"
                ]
            ]
        ],
        [
            "R66",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E61"
                ],
                [
                    "Arg2",
                    "E60"
                ]
            ]
        ],
        [
            "R67",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T114"
                ],
                [
                    "Arg2",
                    "E61"
                ]
            ]
        ],
        [
            "R68",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E62"
                ],
                [
                    "Arg2",
                    "E60"
                ]
            ]
        ],
        [
            "R69",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T118"
                ],
                [
                    "Arg2",
                    "E64"
                ]
            ]
        ],
        [
            "R70",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T119"
                ],
                [
                    "Arg2",
                    "E64"
                ]
            ]
        ],
        [
            "R71",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T122"
                ],
                [
                    "Arg2",
                    "E66"
                ]
            ]
        ],
        [
            "R72",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T123"
                ],
                [
                    "Arg2",
                    "E66"
                ]
            ]
        ],
        [
            "R73",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T125"
                ],
                [
                    "Arg2",
                    "E67"
                ]
            ]
        ],
        [
            "R74",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T127"
                ],
                [
                    "Arg2",
                    "E68"
                ]
            ]
        ],
        [
            "R75",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T131"
                ],
                [
                    "Arg2",
                    "E71"
                ]
            ]
        ],
        [
            "R76",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T134"
                ],
                [
                    "Arg2",
                    "E73"
                ]
            ]
        ],
        [
            "R77",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T136"
                ],
                [
                    "Arg2",
                    "E74"
                ]
            ]
        ],
        [
            "R78",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T137"
                ],
                [
                    "Arg2",
                    "E74"
                ]
            ]
        ],
        [
            "R79",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T140"
                ],
                [
                    "Arg2",
                    "E75"
                ]
            ]
        ],
        [
            "R80",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T139"
                ],
                [
                    "Arg2",
                    "E75"
                ]
            ]
        ],
        [
            "R81",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T144"
                ],
                [
                    "Arg2",
                    "E77"
                ]
            ]
        ],
        [
            "R82",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T143"
                ],
                [
                    "Arg2",
                    "E77"
                ]
            ]
        ],
        [
            "R83",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E1"
                ],
                [
                    "Arg2",
                    "E2"
                ]
            ]
        ],
        [
            "R84",
            "AFTER",
            [
                [
                    "Arg1",
                    "E2"
                ],
                [
                    "Arg2",
                    "E3"
                ]
            ]
        ],
        [
            "R85",
            "AFTER",
            [
                [
                    "Arg1",
                    "E4"
                ],
                [
                    "Arg2",
                    "E6"
                ]
            ]
        ],
        [
            "R86",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E7"
                ],
                [
                    "Arg2",
                    "E8"
                ]
            ]
        ],
        [
            "R87",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E27"
                ],
                [
                    "Arg2",
                    "E29"
                ]
            ]
        ],
        [
            "R88",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E29"
                ],
                [
                    "Arg2",
                    "E34"
                ]
            ]
        ],
        [
            "R89",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E31"
                ],
                [
                    "Arg2",
                    "E30"
                ]
            ]
        ],
        [
            "R90",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E33"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ],
        [
            "R91",
            "AFTER",
            [
                [
                    "Arg1",
                    "E34"
                ],
                [
                    "Arg2",
                    "E35"
                ]
            ]
        ],
        [
            "R92",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E35"
                ],
                [
                    "Arg2",
                    "E36"
                ]
            ]
        ],
        [
            "R93",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E36"
                ],
                [
                    "Arg2",
                    "E37"
                ]
            ]
        ],
        [
            "R94",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E56"
                ],
                [
                    "Arg2",
                    "E57"
                ]
            ]
        ],
        [
            "R95",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E58"
                ],
                [
                    "Arg2",
                    "E60"
                ]
            ]
        ],
        [
            "R96",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E60"
                ],
                [
                    "Arg2",
                    "E63"
                ]
            ]
        ],
        [
            "R97",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E64"
                ],
                [
                    "Arg2",
                    "E65"
                ]
            ]
        ],
        [
            "R98",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E71"
                ],
                [
                    "Arg2",
                    "E72"
                ]
            ]
        ],
        [
            "R99",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E77"
                ],
                [
                    "Arg2",
                    "E75"
                ]
            ]
        ]
    ],
    "triggers": [
        [
            "T3",
            "Activity",
            [
                [
                    44,
                    61
                ]
            ]
        ],
        [
            "T5",
            "Clinical_event",
            [
                [
                    62,
                    69
                ]
            ]
        ],
        [
            "T7",
            "Sign_symptom",
            [
                [
                    122,
                    128
                ]
            ]
        ],
        [
            "T8",
            "Diagnostic_procedure",
            [
                [
                    132,
                    137
                ]
            ]
        ],
        [
            "T11",
            "Duration",
            [
                [
                    25,
                    32
                ]
            ]
        ],
        [
            "T13",
            "Medication",
            [
                [
                    214,
                    228
                ]
            ]
        ],
        [
            "T14",
            "Medication",
            [
                [
                    232,
                    251
                ]
            ]
        ],
        [
            "T15",
            "Diagnostic_procedure",
            [
                [
                    255,
                    274
                ]
            ]
        ],
        [
            "T16",
            "Diagnostic_procedure",
            [
                [
                    276,
                    278
                ]
            ]
        ],
        [
            "T17",
            "Sign_symptom",
            [
                [
                    301,
                    305
                ]
            ]
        ],
        [
            "T23",
            "Sign_symptom",
            [
                [
                    456,
                    466
                ]
            ]
        ],
        [
            "T26",
            "Disease_disorder",
            [
                [
                    499,
                    515
                ]
            ]
        ],
        [
            "T28",
            "Sign_symptom",
            [
                [
                    553,
                    559
                ]
            ]
        ],
        [
            "T32",
            "Coreference",
            [
                [
                    635,
                    645
                ]
            ]
        ],
        [
            "T36",
            "Sign_symptom",
            [
                [
                    712,
                    721
                ]
            ]
        ],
        [
            "T39",
            "Diagnostic_procedure",
            [
                [
                    727,
                    746
                ]
            ]
        ],
        [
            "T40",
            "Diagnostic_procedure",
            [
                [
                    764,
                    786
                ]
            ]
        ],
        [
            "T41",
            "Diagnostic_procedure",
            [
                [
                    799,
                    809
                ]
            ]
        ],
        [
            "T42",
            "Diagnostic_procedure",
            [
                [
                    821,
                    835
                ]
            ]
        ],
        [
            "T43",
            "Diagnostic_procedure",
            [
                [
                    849,
                    871
                ]
            ]
        ],
        [
            "T44",
            "Diagnostic_procedure",
            [
                [
                    881,
                    901
                ]
            ]
        ],
        [
            "T45",
            "Diagnostic_procedure",
            [
                [
                    915,
                    936
                ]
            ]
        ],
        [
            "T46",
            "Diagnostic_procedure",
            [
                [
                    938,
                    941
                ]
            ]
        ],
        [
            "T53",
            "Sign_symptom",
            [
                [
                    956,
                    981
                ]
            ]
        ],
        [
            "T54",
            "Diagnostic_procedure",
            [
                [
                    1007,
                    1031
                ]
            ]
        ],
        [
            "T55",
            "Diagnostic_procedure",
            [
                [
                    1064,
                    1076
                ]
            ]
        ],
        [
            "T56",
            "Disease_disorder",
            [
                [
                    1104,
                    1124
                ]
            ]
        ],
        [
            "T57",
            "Sign_symptom",
            [
                [
                    1037,
                    1042
                ]
            ]
        ],
        [
            "T58",
            "Medication",
            [
                [
                    1246,
                    1258
                ]
            ]
        ],
        [
            "T60",
            "Medication",
            [
                [
                    1273,
                    1282
                ]
            ]
        ],
        [
            "T62",
            "Date",
            [
                [
                    1314,
                    1319
                ]
            ]
        ],
        [
            "T63",
            "Medication",
            [
                [
                    1325,
                    1334
                ]
            ]
        ],
        [
            "T65",
            "Date",
            [
                [
                    1367,
                    1375
                ]
            ]
        ],
        [
            "T66",
            "Date",
            [
                [
                    1381,
                    1400
                ]
            ]
        ],
        [
            "T67",
            "Diagnostic_procedure",
            [
                [
                    1418,
                    1420
                ]
            ]
        ],
        [
            "T68",
            "Medication",
            [
                [
                    1448,
                    1460
                ]
            ]
        ],
        [
            "T69",
            "Date",
            [
                [
                    1473,
                    1478
                ]
            ]
        ],
        [
            "T70",
            "Sign_symptom",
            [
                [
                    1537,
                    1547
                ]
            ]
        ],
        [
            "T72",
            "Diagnostic_procedure",
            [
                [
                    1557,
                    1568
                ]
            ]
        ],
        [
            "T73",
            "Sign_symptom",
            [
                [
                    1576,
                    1587
                ]
            ]
        ],
        [
            "T75",
            "Sign_symptom",
            [
                [
                    1615,
                    1626
                ]
            ]
        ],
        [
            "T77",
            "Diagnostic_procedure",
            [
                [
                    1643,
                    1668
                ]
            ]
        ],
        [
            "T78",
            "Sign_symptom",
            [
                [
                    1683,
                    1689
                ]
            ]
        ],
        [
            "T80",
            "Diagnostic_procedure",
            [
                [
                    1691,
                    1701
                ]
            ]
        ],
        [
            "T83",
            "Duration",
            [
                [
                    1757,
                    1769
                ]
            ]
        ],
        [
            "T85",
            "Diagnostic_procedure",
            [
                [
                    1834,
                    1843
                ]
            ]
        ],
        [
            "T87",
            "Diagnostic_procedure",
            [
                [
                    1864,
                    1866
                ]
            ]
        ],
        [
            "T88",
            "Sign_symptom",
            [
                [
                    1891,
                    1902
                ]
            ]
        ],
        [
            "T90",
            "Sign_symptom",
            [
                [
                    1914,
                    1919
                ]
            ]
        ],
        [
            "T93",
            "Sign_symptom",
            [
                [
                    1962,
                    1980
                ]
            ]
        ],
        [
            "T95",
            "Diagnostic_procedure",
            [
                [
                    1988,
                    1998
                ]
            ]
        ],
        [
            "T96",
            "Sign_symptom",
            [
                [
                    2028,
                    2035
                ]
            ]
        ],
        [
            "T98",
            "Sign_symptom",
            [
                [
                    2103,
                    2113
                ]
            ]
        ],
        [
            "T101",
            "Sign_symptom",
            [
                [
                    2141,
                    2148
                ]
            ]
        ],
        [
            "T103",
            "Diagnostic_procedure",
            [
                [
                    2189,
                    2191
                ]
            ]
        ],
        [
            "T105",
            "Sign_symptom",
            [
                [
                    2215,
                    2228
                ]
            ]
        ],
        [
            "T106",
            "Diagnostic_procedure",
            [
                [
                    2243,
                    2254
                ]
            ]
        ],
        [
            "T108",
            "Sign_symptom",
            [
                [
                    2372,
                    2385
                ]
            ]
        ],
        [
            "T109",
            "Sign_symptom",
            [
                [
                    2325,
                    2338
                ]
            ]
        ],
        [
            "T112",
            "Therapeutic_procedure",
            [
                [
                    2646,
                    2681
                ]
            ]
        ],
        [
            "T113",
            "Therapeutic_procedure",
            [
                [
                    2683,
                    2686
                ]
            ]
        ],
        [
            "T115",
            "Therapeutic_procedure",
            [
                [
                    2726,
                    2743
                ]
            ]
        ],
        [
            "T116",
            "Diagnostic_procedure",
            [
                [
                    2793,
                    2804
                ]
            ]
        ],
        [
            "T117",
            "Diagnostic_procedure",
            [
                [
                    2823,
                    2833
                ]
            ]
        ],
        [
            "T120",
            "Therapeutic_procedure",
            [
                [
                    2962,
                    2982
                ]
            ]
        ],
        [
            "T121",
            "Medication",
            [
                [
                    2994,
                    2997
                ]
            ]
        ],
        [
            "T124",
            "Diagnostic_procedure",
            [
                [
                    3032,
                    3047
                ]
            ]
        ],
        [
            "T126",
            "Diagnostic_procedure",
            [
                [
                    3079,
                    3093
                ]
            ]
        ],
        [
            "T128",
            "Sign_symptom",
            [
                [
                    3123,
                    3134
                ]
            ]
        ],
        [
            "T129",
            "Sign_symptom",
            [
                [
                    3156,
                    3162
                ]
            ]
        ],
        [
            "T130",
            "Sign_symptom",
            [
                [
                    3228,
                    3239
                ]
            ]
        ],
        [
            "T132",
            "Date",
            [
                [
                    3256,
                    3269
                ]
            ]
        ],
        [
            "T133",
            "Diagnostic_procedure",
            [
                [
                    3314,
                    3320
                ]
            ]
        ],
        [
            "T135",
            "Medication",
            [
                [
                    3350,
                    3362
                ]
            ]
        ],
        [
            "T138",
            "Diagnostic_procedure",
            [
                [
                    3436,
                    3444
                ]
            ]
        ],
        [
            "T141",
            "Medication",
            [
                [
                    3462,
                    3474
                ]
            ]
        ],
        [
            "T142",
            "Sign_symptom",
            [
                [
                    3503,
                    3510
                ]
            ]
        ]
    ],
    "events": [
        [
            "E1",
            "T3",
            []
        ],
        [
            "E2",
            "T5",
            []
        ],
        [
            "E3",
            "T7",
            []
        ],
        [
            "E4",
            "T8",
            []
        ],
        [
            "E5",
            "T11",
            []
        ],
        [
            "E6",
            "T13",
            []
        ],
        [
            "E7",
            "T14",
            []
        ],
        [
            "E8",
            "T15",
            []
        ],
        [
            "E9",
            "T16",
            []
        ],
        [
            "E10",
            "T17",
            []
        ],
        [
            "E11",
            "T23",
            []
        ],
        [
            "E12",
            "T26",
            []
        ],
        [
            "E13",
            "T28",
            []
        ],
        [
            "E14",
            "T32",
            []
        ],
        [
            "E15",
            "T36",
            []
        ],
        [
            "E16",
            "T39",
            []
        ],
        [
            "E17",
            "T40",
            []
        ],
        [
            "E18",
            "T41",
            []
        ],
        [
            "E19",
            "T42",
            []
        ],
        [
            "E20",
            "T43",
            []
        ],
        [
            "E21",
            "T44",
            []
        ],
        [
            "E22",
            "T45",
            []
        ],
        [
            "E23",
            "T46",
            []
        ],
        [
            "E24",
            "T53",
            []
        ],
        [
            "E25",
            "T54",
            []
        ],
        [
            "E26",
            "T55",
            []
        ],
        [
            "E27",
            "T56",
            []
        ],
        [
            "E28",
            "T57",
            []
        ],
        [
            "E29",
            "T58",
            []
        ],
        [
            "E30",
            "T60",
            []
        ],
        [
            "E31",
            "T62",
            []
        ],
        [
            "E32",
            "T63",
            []
        ],
        [
            "E33",
            "T65",
            []
        ],
        [
            "E34",
            "T66",
            []
        ],
        [
            "E35",
            "T67",
            []
        ],
        [
            "E36",
            "T68",
            []
        ],
        [
            "E37",
            "T69",
            []
        ],
        [
            "E38",
            "T70",
            []
        ],
        [
            "E39",
            "T72",
            []
        ],
        [
            "E40",
            "T73",
            []
        ],
        [
            "E41",
            "T75",
            []
        ],
        [
            "E42",
            "T77",
            []
        ],
        [
            "E43",
            "T78",
            []
        ],
        [
            "E44",
            "T80",
            []
        ],
        [
            "E45",
            "T83",
            []
        ],
        [
            "E46",
            "T85",
            []
        ],
        [
            "E47",
            "T87",
            []
        ],
        [
            "E48",
            "T88",
            []
        ],
        [
            "E49",
            "T90",
            []
        ],
        [
            "E50",
            "T93",
            []
        ],
        [
            "E51",
            "T95",
            []
        ],
        [
            "E52",
            "T96",
            []
        ],
        [
            "E53",
            "T98",
            []
        ],
        [
            "E54",
            "T101",
            []
        ],
        [
            "E55",
            "T103",
            []
        ],
        [
            "E56",
            "T105",
            []
        ],
        [
            "E57",
            "T106",
            []
        ],
        [
            "E58",
            "T108",
            []
        ],
        [
            "E59",
            "T109",
            []
        ],
        [
            "E60",
            "T112",
            []
        ],
        [
            "E61",
            "T113",
            []
        ],
        [
            "E62",
            "T115",
            []
        ],
        [
            "E63",
            "T116",
            []
        ],
        [
            "E64",
            "T117",
            []
        ],
        [
            "E65",
            "T120",
            []
        ],
        [
            "E66",
            "T121",
            []
        ],
        [
            "E67",
            "T124",
            []
        ],
        [
            "E68",
            "T126",
            []
        ],
        [
            "E69",
            "T128",
            []
        ],
        [
            "E70",
            "T129",
            []
        ],
        [
            "E71",
            "T130",
            []
        ],
        [
            "E72",
            "T132",
            []
        ],
        [
            "E73",
            "T133",
            []
        ],
        [
            "E74",
            "T135",
            []
        ],
        [
            "E75",
            "T138",
            []
        ],
        [
            "E76",
            "T141",
            []
        ],
        [
            "E77",
            "T142",
            []
        ]
    ],
    "equivs": [
        [
            "*",
            "OVERLAP",
            "E3",
            "E4"
        ],
        [
            "*",
            "OVERLAP",
            "E6",
            "E7"
        ],
        [
            "*",
            "OVERLAP",
            "E8",
            "E10",
            "E11",
            "E12",
            "E13",
            "E14",
            "E15",
            "E16",
            "E24",
            "E25",
            "E26",
            "E27"
        ],
        [
            "*",
            "OVERLAP",
            "E37",
            "E38",
            "E39",
            "E42",
            "E46",
            "E47",
            "E48",
            "E49",
            "E50",
            "E52",
            "E53",
            "E54",
            "E55",
            "E56"
        ],
        [
            "*",
            "OVERLAP",
            "E57",
            "E59",
            "E58"
        ],
        [
            "*",
            "OVERLAP",
            "E63",
            "E64"
        ],
        [
            "*",
            "OVERLAP",
            "E65",
            "E66",
            "E67",
            "E68",
            "E69",
            "E70",
            "E71"
        ],
        [
            "*",
            "OVERLAP",
            "E72",
            "E73",
            "E74",
            "E75",
            "E76",
            "E77"
        ]
    ],
    "comments": [
        [
            "T74",
            "AnnotatorNotes",
            "implicit heart rate measurement"
        ],
        [
            "T76",
            "AnnotatorNotes",
            "implicit blood pressure measurement"
        ],
        [
            "E66",
            "AnnotatorNotes",
            "red blood cells"
        ]
    ],
    "pmID": 28321073,
    "text": "A 65-year-old man with a 45-year history of cigarette smoking visited our hospital for the diagnosis of an abnormal chest shadow on X-ray.\nHe did not have any remarkable medical history and had not been prescribed anticoagulants or antiplatelet agents.\nA computed tomography (CT) scan revealed a huge mass in the left upper lobe (maximum size: 11.0 cm in diameter) that subsequently expanded to the left hilum and mediastinum, as well as an intrapulmonary metastasis located in the left lower lobe, pleural effusion on the left side, and multiple liver tumors ranging from 0.5 to 4.7 cm in diameter (Fig.1).\nOf note, some of the liver metastases were located subcapsularly, and the liver surface was irregularly distorted.\nThe laboratory findings were as follows: white blood cell count 11,900/mm3, hemoglobin 14.8 g/dL, platelet count 214,000/mm3, aspartate transaminase 31 IU/L, alanine transaminase 19 IU/L, and lactate dehydrogenase (LDH) 749 IU/L.\nNo coagulation abnormalities were found.\nA subsequent histological examination of a tumor specimen obtained by bronchoscopy confirmed the diagnosis of small cell carcinoma.\nOn considering the clinical diagnosis, performance status, and age of the patient, we decided on a regimen of antitumor chemotherapy consisting of cisplatin (60 mg/m2 body surface area on Day 1) and etoposide (100 mg/m2 body surface area on Days 1-3).\nOn a day after 2 weeks from the initial CT scan, he started his first chemotherapy session.\nOn Day 3 after initiating chemotherapy, he complained of abdominal discomfort, and his vital signs showed tachycardia (120 beats per minute) and hypotension (85/55 mmHg).\nA hematological examination showed severe anemia (hemoglobin 6.7 g/dL) that had dramatically dropped from 14.8 g/dL over 10 days.\nWe attempted to identify the bleeding site on gastrointestinal endoscopy, to no avail, but a CT scan revealed the rapid enlargement of a liver tumor in the left lobe, which contained partial high-density areas on the plain scan, and also a novel finding of ascites showing higher density than usual, all suggesting a ruptured liver metastasis and associated hemorrhagic ascites (Fig.2).\nA subsequent contrast-enhanced CT image was negative for extravasation.\nHe underwent angiography for the left and right hepatic arteries, but we only observed obscure tumor vessels in the left hepatic lobe without extravasation (Fig.3A).\nWe suspected this might be due to the hypovascularity of the metastatic tumors and inactive bleeding at the time.\nAlthough the benefit of therapeutic embolization of the hepatic artery was uncertain based on the findings on angiography, we performed transcatheter arterial embolization (TAE) of the left main hepatic artery using gelform particles to prevent future re-bleeding.\nPost-embolization angiography revealed a slowed blood flow in the left hepatic artery, and the peripheral vessels were weakly visualized (Fig.3B).\nAfter the embolization concomitant with supportive therapies, including RBC transfusions of 6 U in total, the clinical course of the patient stabilized.\nHis blood pressure remained around 120/70 mmHg, tachycardia disappeared, and the anemia was improved after transfusion and did not progress again.\nLiver dysfunction did not appear.\nA month after the embolization, he was in relatively good health and re-started his antitumor chemotherapy, which he continued (first-line regimen) for six courses.\nA good partial response was gained after chemotherapy for both the lung and liver lesions.",
    "action": "getDocument",
    "createdAt": {
        "$date": "2019-04-15T17:53:41.980Z"
    },
    "updatedAt": {
        "$date": "2019-04-15T17:53:41.980Z"
    },
    "__v": 0
};
    // console.log('data:', graphData);
    
    // Create the Elements (Nodes) to be visualized
    var elements = buildGraphElementsFromGraphData(graphData);

    // // From Entities
    // var nID2index = new Map();
    // for (i=0; i < graphData.entities.length; i++) {
    //   const nodeID = graphData.entities[i][0];
    //   const nodeTextSIndex = graphData.entities[i][2][0][0];
    //   const nodeTextEIndex = graphData.entities[i][2][0][1];
    //   // const nodeText = graphData.text.substring(nodeTextSIndex,nodeTextEIndex);
    //   // elements.push( {
    //   //   data: {
    //   //     id: nodeID, 
    //   //     label: nodeText
    //   //   }
    //   // });
    //   nID2index.set(nodeID, [nodeTextSIndex, nodeTextEIndex]);
    // }
    // // From Triggers
    // for (i=0; i < graphData.triggers.length; i++) {
    //   const nodeID = graphData.triggers[i][0];
    //   const nodeTextSIndex = graphData.triggers[i][2][0][0];
    //   const nodeTextEIndex = graphData.triggers[i][2][0][1];
    //   // const nodeText = graphData.text.substring(nodeTextSIndex,nodeTextEIndex);
    //   // elements.push( {
    //   //   data: {
    //   //     id: nodeID, 
    //   //     label: nodeText
    //   //   }
    //   // });
    //   nID2index.set(nodeID, [nodeTextSIndex, nodeTextEIndex]);
    // }

    // // Create the Edges to be visualized
    // // First map all events to a node
    // var eID2nID = new Map();
    // for (i=0; i<graphData.events.length; i++) {
    //   const eventID = graphData.events[i][0];
    //   const nodeID = graphData.events[i][1];
    //   eID2nID.set(eventID, nodeID);
    // }
    // // From Relatiosn
    // var nodeSet = new Set();
    // for (var i=0; i < graphData.relations.length; i++) {
    //   const eventID_1 = graphData.relations[i][2][0][1];
    //   const eventID_2 = graphData.relations[i][2][1][1];
    //   const event_label = graphData.relations[i][1];
    //   // if (event_label=='BEFORE') {
    //     // continue;
    //   // }
    //   const sourcID = eID2nID.has(eventID_1) ? eID2nID.get(eventID_1) : eventID_1;
    //   const targetID = eID2nID.has(eventID_2) ? eID2nID.get(eventID_2) : eventID_2;

    //   var nodeText;
    //   if (!nodeSet.has(sourcID)) {
    //     nodeText = graphData.text.substring(nID2index.get(sourcID)[0], nID2index.get(sourcID)[1]);
    //     nodeText = nodeText.length>15 ? nodeText.substring(0,15) : nodeText;
    //     elements.push( {
    //       data: {
    //         id: sourcID,
    //         label: nodeText
    //       }
    //     });
    //     nodeSet.add(sourcID);
    //   }

    //   if (!nodeSet.has(targetID)) {
    //     nodeText = graphData.text.substring(nID2index.get(targetID)[0], nID2index.get(targetID)[1]);
    //     nodeText = nodeText.length>15 ? nodeText.substring(0,15) : nodeText;
    //     elements.push( {
    //       data: {
    //         id: targetID,
    //         label: nodeText
    //       }
    //     });
    //     nodeSet.add(targetID);
    //   }
    //   var color="rgb(1, 136, 203)";
    //   // if (event_label=='BEFORE'){
    //   //   color = 'red';
    //   // }
    //   // else if (event_label=='MODIFY') {
    //   //   color = 'blue';
    //   // }
    //   // else if (event_label=='IDENTICAL') {
    //   //   color = 'green';
    //   // }
    //   elements.push( {
    //     data: {
    //       source: sourcID,
    //       target: targetID,
    //       label: event_label,
    //       arrow: 'triangle',
    //       c: color
    //     }
    //   });
      // }

      // else if (event_label=='MODIFY') {
      //   const sourcID = eID2nID.has(eventID_1) ? eID2nID.get(eventID_1) : eventID_1;
      //   const targetID = eID2nID.has(eventID_2) ? eID2nID.get(eventID_2) : eventID_2;

      // // if (!nodeSet.has(sourcID)) {
      //   elements2.push( {
      //     data: {
      //       id: sourcID,
      //       label: graphData.text.substring(nID2index.get(sourcID)[0], nID2index.get(sourcID)[1])
      //     }
      //   });
      //   nodeSet.add(sourcID);
      // // }

      // // if (!nodeSet.has(targetID)) {
      //   elements2.push( {
      //     data: {
      //       id: targetID,
      //       label: graphData.text.substring(nID2index.get(targetID)[0], nID2index.get(targetID)[1])
      //     }
      //   });
      //   nodeSet.add(targetID);
      // // }

      //   elements2.push( {
      //     data: {
      //       source: sourcID,
      //       target: targetID,
      //       label: event_label,
      //       arrow: 'triangle'
      //     }
      //   });
      // }
    // }
    // Layout
    const layout = {
      name: 'dagre',
      nodeSep: 100,
      nodeDimensionsIncludeLabels: true
      // ranker: "longest-path"
      // name: 'breadthfirst',
      // directed: true,
      // padding: 10
    };

    const stylesheet = [
        {
          "selector": "node[type]",
          "style": {
            "content": "data(label)",
            "text-valign": "center",
            "text-halign": "center",
            // "text-font-size": 100,
            "width": 60,
            "height": 60,
            "shape": "data(type)",
            "background-color": "rgb(244, 149, 65)",              // node color
            "text-outline-color": "rgb(244, 149, 65)",
            "text-outline-opacity": 1,
            "text-outline-width": 0,
            "color": "black",                                     // text color
            "overlay-color": "#fff"
          }
        },
        {
          "selector": "edge",
          "style": {
            "width": 3,
            "curve-style": "straight"
          }
        },
        {
          "selector": "edge[arrow]",
          "style": {
            "target-arrow-shape": "data(arrow)",
            "line-color": "data(c)"
          }
        }
      ]
    

    // elements.push( { data: { id: 'three', label: 'Node 3' }, position: { x: 500, y: 250 } } );
    // elements.push( {data: { source: 'three', target: 'two', label: 'Edge from Node3 to Node2'}});
    return (
      <div>
      <div>
      <CytoscapeComponent 
        elements={elements} 
        style={ { width: '100%', height: '500px'}} 
        layout={layout} 
        stylesheet={stylesheet} ></CytoscapeComponent>
      </div>
      </div>
    );
  }
}
export default Graph;
