const docData = {
    "_id": {
        "$oid": "5c8eea57ca49b8479b8938db"
    },
    "messages": [],
    "source_files": [
        "ann",
        "txt"
    ],
    "modifications": [],
    "normalizations": [],
    "entities": [
        [
            "T1",
            "Age",
            [
                [
                    2,
                    13
                ]
            ]
        ],
        [
            "T2",
            "Sex",
            [
                [
                    14,
                    17
                ]
            ]
        ],
        [
            "T5",
            "Distance",
            [
                [
                    64,
                    68
                ]
            ]
        ],
        [
            "T6",
            "Distance",
            [
                [
                    100,
                    105
                ]
            ]
        ],
        [
            "T7",
            "Biological_structure",
            [
                [
                    115,
                    125
                ]
            ]
        ],
        [
            "T16",
            "Detailed_description",
            [
                [
                    291,
                    297
                ]
            ]
        ],
        [
            "T17",
            "Lab_value",
            [
                [
                    360,
                    368
                ]
            ]
        ],
        [
            "T21",
            "Distance",
            [
                [
                    477,
                    481
                ]
            ]
        ],
        [
            "T22",
            "Distance",
            [
                [
                    494,
                    499
                ]
            ]
        ],
        [
            "T23",
            "Biological_structure",
            [
                [
                    509,
                    519
                ]
            ]
        ],
        [
            "T29",
            "Biological_structure",
            [
                [
                    755,
                    761
                ]
            ]
        ],
        [
            "T34",
            "Biological_structure",
            [
                [
                    907,
                    913
                ]
            ]
        ],
        [
            "T35",
            "Biological_structure",
            [
                [
                    933,
                    951
                ]
            ]
        ],
        [
            "T36",
            "Detailed_description",
            [
                [
                    898,
                    906
                ]
            ]
        ],
        [
            "T39",
            "Biological_structure",
            [
                [
                    1043,
                    1049
                ]
            ]
        ],
        [
            "T42",
            "Biological_structure",
            [
                [
                    1099,
                    1105
                ]
            ]
        ],
        [
            "T43",
            "Biological_structure",
            [
                [
                    1125,
                    1131
                ]
            ]
        ],
        [
            "T44",
            "Biological_structure",
            [
                [
                    1136,
                    1145
                ]
            ]
        ],
        [
            "T50",
            "Biological_structure",
            [
                [
                    1496,
                    1517
                ]
            ]
        ],
        [
            "T59",
            "Biological_structure",
            [
                [
                    1644,
                    1653
                ]
            ]
        ],
        [
            "T60",
            "Biological_structure",
            [
                [
                    1662,
                    1684
                ]
            ]
        ],
        [
            "T61",
            "Lab_value",
            [
                [
                    1639,
                    1643
                ]
            ]
        ],
        [
            "T62",
            "Lab_value",
            [
                [
                    1658,
                    1661
                ]
            ]
        ]
    ],
    "attributes": [
        [
            "A1",
            "POLARITY",
            "E24",
            "NEG"
        ],
        [
            "A2",
            "POLARITY",
            "E34",
            "NEG"
        ],
        [
            "A3",
            "POLARITY",
            "E38",
            "NEG"
        ]
    ],
    "relations": [
        [
            "R1",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T5"
                ],
                [
                    "Arg2",
                    "E2"
                ]
            ]
        ],
        [
            "R2",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T6"
                ],
                [
                    "Arg2",
                    "T7"
                ]
            ]
        ],
        [
            "R3",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T7"
                ],
                [
                    "Arg2",
                    "E2"
                ]
            ]
        ],
        [
            "R4",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E5"
                ],
                [
                    "Arg2",
                    "E2"
                ]
            ]
        ],
        [
            "R6",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E10"
                ],
                [
                    "Arg2",
                    "E9"
                ]
            ]
        ],
        [
            "R7",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T16"
                ],
                [
                    "Arg2",
                    "E9"
                ]
            ]
        ],
        [
            "R8",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T17"
                ],
                [
                    "Arg2",
                    "E9"
                ]
            ]
        ],
        [
            "R9",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T17"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R10",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T21"
                ],
                [
                    "Arg2",
                    "E13"
                ]
            ]
        ],
        [
            "R11",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T22"
                ],
                [
                    "Arg2",
                    "T23"
                ]
            ]
        ],
        [
            "R12",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T23"
                ],
                [
                    "Arg2",
                    "E13"
                ]
            ]
        ],
        [
            "R13",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E16"
                ],
                [
                    "Arg2",
                    "E15"
                ]
            ]
        ],
        [
            "R5",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E6"
                ],
                [
                    "Arg2",
                    "E4"
                ]
            ]
        ],
        [
            "R14",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T29"
                ],
                [
                    "Arg2",
                    "E17"
                ]
            ]
        ],
        [
            "R15",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E18"
                ],
                [
                    "Arg2",
                    "E17"
                ]
            ]
        ],
        [
            "R16",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E20"
                ],
                [
                    "Arg2",
                    "E19"
                ]
            ]
        ],
        [
            "R17",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E21"
                ],
                [
                    "Arg2",
                    "E17"
                ]
            ]
        ],
        [
            "R18",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T34"
                ],
                [
                    "Arg2",
                    "E22"
                ]
            ]
        ],
        [
            "R19",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T35"
                ],
                [
                    "Arg2",
                    "E22"
                ]
            ]
        ],
        [
            "R20",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T36"
                ],
                [
                    "Arg2",
                    "E22"
                ]
            ]
        ],
        [
            "R21",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T39"
                ],
                [
                    "Arg2",
                    "E24"
                ]
            ]
        ],
        [
            "R22",
            "IDENTICAL",
            [
                [
                    "Arg1",
                    "E25"
                ],
                [
                    "Arg2",
                    "E20"
                ]
            ]
        ],
        [
            "R23",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T42"
                ],
                [
                    "Arg2",
                    "E26"
                ]
            ]
        ],
        [
            "R24",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T43"
                ],
                [
                    "Arg2",
                    "E26"
                ]
            ]
        ],
        [
            "R25",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T44"
                ],
                [
                    "Arg2",
                    "E26"
                ]
            ]
        ],
        [
            "R26",
            "SUB_PROCEDURE",
            [
                [
                    "Arg1",
                    "E28"
                ],
                [
                    "Arg2",
                    "E27"
                ]
            ]
        ],
        [
            "R27",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T50"
                ],
                [
                    "Arg2",
                    "E31"
                ]
            ]
        ],
        [
            "R28",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E33"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ],
        [
            "R29",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T59"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R30",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T60"
                ],
                [
                    "Arg2",
                    "E39"
                ]
            ]
        ],
        [
            "R31",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T61"
                ],
                [
                    "Arg2",
                    "T59"
                ]
            ]
        ],
        [
            "R32",
            "MODIFY",
            [
                [
                    "Arg1",
                    "T62"
                ],
                [
                    "Arg2",
                    "T60"
                ]
            ]
        ],
        [
            "R33",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E40"
                ],
                [
                    "Arg2",
                    "T59"
                ]
            ]
        ],
        [
            "R34",
            "MODIFY",
            [
                [
                    "Arg1",
                    "E40"
                ],
                [
                    "Arg2",
                    "T60"
                ]
            ]
        ],
        [
            "R35",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E4"
                ],
                [
                    "Arg2",
                    "E7"
                ]
            ]
        ],
        [
            "R36",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E9"
                ],
                [
                    "Arg2",
                    "E11"
                ]
            ]
        ],
        [
            "R37",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E26"
                ],
                [
                    "Arg2",
                    "E27"
                ]
            ]
        ],
        [
            "R38",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E30"
                ],
                [
                    "Arg2",
                    "E31"
                ]
            ]
        ],
        [
            "R39",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E40"
                ],
                [
                    "Arg2",
                    "E35"
                ]
            ]
        ]
    ],
    "triggers": [
        [
            "T3",
            "Diagnostic_procedure",
            [
                [
                    32,
                    43
                ]
            ]
        ],
        [
            "T4",
            "Sign_symptom",
            [
                [
                    69,
                    82
                ]
            ]
        ],
        [
            "T8",
            "Therapeutic_procedure",
            [
                [
                    130,
                    150
                ]
            ]
        ],
        [
            "T9",
            "Disease_disorder",
            [
                [
                    168,
                    189
                ]
            ]
        ],
        [
            "T10",
            "Coreference",
            [
                [
                    156,
                    161
                ]
            ]
        ],
        [
            "T11",
            "Sign_symptom",
            [
                [
                    201,
                    221
                ]
            ]
        ],
        [
            "T12",
            "Diagnostic_procedure",
            [
                [
                    225,
                    247
                ]
            ]
        ],
        [
            "T13",
            "Date",
            [
                [
                    258,
                    276
                ]
            ]
        ],
        [
            "T14",
            "Diagnostic_procedure",
            [
                [
                    298,
                    309
                ]
            ]
        ],
        [
            "T15",
            "Date",
            [
                [
                    310,
                    348
                ]
            ]
        ],
        [
            "T18",
            "Diagnostic_procedure",
            [
                [
                    387,
                    398
                ]
            ]
        ],
        [
            "T19",
            "Date",
            [
                [
                    409,
                    450
                ]
            ]
        ],
        [
            "T20",
            "Sign_symptom",
            [
                [
                    462,
                    475
                ]
            ]
        ],
        [
            "T24",
            "Diagnostic_procedure",
            [
                [
                    521,
                    529
                ]
            ]
        ],
        [
            "T25",
            "Disease_disorder",
            [
                [
                    575,
                    590
                ]
            ]
        ],
        [
            "T26",
            "Sign_symptom",
            [
                [
                    596,
                    615
                ]
            ]
        ],
        [
            "T27",
            "Diagnostic_procedure",
            [
                [
                    762,
                    788
                ]
            ]
        ],
        [
            "T28",
            "Diagnostic_procedure",
            [
                [
                    790,
                    793
                ]
            ]
        ],
        [
            "T30",
            "Diagnostic_procedure",
            [
                [
                    807,
                    828
                ]
            ]
        ],
        [
            "T31",
            "Diagnostic_procedure",
            [
                [
                    830,
                    833
                ]
            ]
        ],
        [
            "T32",
            "Coreference",
            [
                [
                    882,
                    885
                ]
            ]
        ],
        [
            "T33",
            "Sign_symptom",
            [
                [
                    914,
                    918
                ]
            ]
        ],
        [
            "T37",
            "Disease_disorder",
            [
                [
                    1008,
                    1027
                ]
            ]
        ],
        [
            "T38",
            "Sign_symptom",
            [
                [
                    1050,
                    1065
                ]
            ]
        ],
        [
            "T40",
            "Coreference",
            [
                [
                    1084,
                    1087
                ]
            ]
        ],
        [
            "T41",
            "Sign_symptom",
            [
                [
                    1106,
                    1110
                ]
            ]
        ],
        [
            "T45",
            "Therapeutic_procedure",
            [
                [
                    1357,
                    1375
                ]
            ]
        ],
        [
            "T46",
            "Therapeutic_procedure",
            [
                [
                    1401,
                    1423
                ]
            ]
        ],
        [
            "T47",
            "Therapeutic_procedure",
            [
                [
                    1428,
                    1450
                ]
            ]
        ],
        [
            "T48",
            "Therapeutic_procedure",
            [
                [
                    1456,
                    1470
                ]
            ]
        ],
        [
            "T49",
            "Diagnostic_procedure",
            [
                [
                    1472,
                    1488
                ]
            ]
        ],
        [
            "T51",
            "Disease_disorder",
            [
                [
                    1529,
                    1544
                ]
            ]
        ],
        [
            "T52",
            "Sign_symptom",
            [
                [
                    1550,
                    1568
                ]
            ]
        ],
        [
            "T53",
            "Sign_symptom",
            [
                [
                    1595,
                    1622
                ]
            ]
        ],
        [
            "T54",
            "Therapeutic_procedure",
            [
                [
                    1739,
                    1757
                ]
            ]
        ],
        [
            "T55",
            "Date",
            [
                [
                    1758,
                    1775
                ]
            ]
        ],
        [
            "T56",
            "Sign_symptom",
            [
                [
                    1788,
                    1800
                ]
            ]
        ],
        [
            "T57",
            "Sign_symptom",
            [
                [
                    1809,
                    1830
                ]
            ]
        ],
        [
            "T58",
            "Therapeutic_procedure",
            [
                [
                    1690,
                    1697
                ]
            ]
        ],
        [
            "T63",
            "Sign_symptom",
            [
                [
                    1709,
                    1715
                ]
            ]
        ]
    ],
    "events": [
        [
            "E1",
            "T3",
            []
        ],
        [
            "E2",
            "T4",
            []
        ],
        [
            "E3",
            "T8",
            []
        ],
        [
            "E4",
            "T9",
            []
        ],
        [
            "E5",
            "T10",
            []
        ],
        [
            "E6",
            "T11",
            []
        ],
        [
            "E7",
            "T12",
            []
        ],
        [
            "E8",
            "T13",
            []
        ],
        [
            "E9",
            "T14",
            []
        ],
        [
            "E10",
            "T15",
            []
        ],
        [
            "E11",
            "T18",
            []
        ],
        [
            "E12",
            "T19",
            []
        ],
        [
            "E13",
            "T20",
            []
        ],
        [
            "E14",
            "T24",
            []
        ],
        [
            "E15",
            "T25",
            []
        ],
        [
            "E16",
            "T26",
            []
        ],
        [
            "E17",
            "T27",
            []
        ],
        [
            "E18",
            "T28",
            []
        ],
        [
            "E19",
            "T30",
            []
        ],
        [
            "E20",
            "T31",
            []
        ],
        [
            "E21",
            "T32",
            []
        ],
        [
            "E22",
            "T33",
            []
        ],
        [
            "E23",
            "T37",
            []
        ],
        [
            "E24",
            "T38",
            []
        ],
        [
            "E25",
            "T40",
            []
        ],
        [
            "E26",
            "T41",
            []
        ],
        [
            "E27",
            "T45",
            []
        ],
        [
            "E28",
            "T46",
            []
        ],
        [
            "E29",
            "T47",
            []
        ],
        [
            "E30",
            "T48",
            []
        ],
        [
            "E31",
            "T49",
            []
        ],
        [
            "E32",
            "T51",
            []
        ],
        [
            "E33",
            "T52",
            []
        ],
        [
            "E34",
            "T53",
            []
        ],
        [
            "E35",
            "T54",
            []
        ],
        [
            "E36",
            "T55",
            []
        ],
        [
            "E37",
            "T56",
            []
        ],
        [
            "E38",
            "T57",
            []
        ],
        [
            "E39",
            "T58",
            []
        ],
        [
            "E40",
            "T63",
            []
        ]
    ],
    "equivs": [
        [
            "*",
            "OVERLAP",
            "E1",
            "E2",
            "E3",
            "E4"
        ],
        [
            "*",
            "OVERLAP",
            "E7",
            "E8",
            "E9"
        ],
        [
            "*",
            "OVERLAP",
            "E11",
            "E12",
            "E13",
            "E14",
            "E15",
            "E17",
            "E19",
            "E22",
            "E23",
            "E24",
            "E26"
        ],
        [
            "*",
            "OVERLAP",
            "E27",
            "E29",
            "E30"
        ],
        [
            "*",
            "OVERLAP",
            "E31",
            "E32",
            "E34",
            "E39",
            "E40"
        ],
        [
            "*",
            "OVERLAP",
            "E35",
            "E36",
            "E37",
            "E38"
        ]
    ],
    "comments": [],
    "text": "A 60-year-old man who underwent colonoscopy was found to have a 2 cm sessile polyp that was located 10 cm from the anal verge and successfully removed.\nThe polyp was a tubulovillous adenoma with focal high-grade dysplasia.\nA flexible sigmoidoscopy performed three months later, as well as a repeat colonoscopy one year after the initial colonoscopy, were both negative for recurrence.\nA colonoscopy performed three years after the initial colonoscopy revealed a sessile polyp, 3 cm in size, at 10 cm from the anal verge.\nBiopsies were taken and reported to be fragments of a villous adenoma with low-grade dysplasia.\nDue to the previous high-grade dysplasia, relatively rapid recurrence and concern that a cancer may have been missed by sampling error, a pelvic magnetic resonance imaging (MRI) scan and an endoscopic ultrasound (EUS) were performed before definitive excision.\nThe MRI revealed an invasive rectal mass involving the muscularis propria but without breach of the adventitia, consistent with a T2 rectal carcinoma (Figure 1).\nNo pelvic lymphadenopathy was detected.\nThe EUS revealed a rectal mass involving the mucosa and submucosa, with no involvement of the muscularis propria (Figure 2).\nThe results of the MRI and EUS, as well as the surgical versus endoscopic resection treatment options, were discussed with the patient, who opted for a surgical resection.\nThe patient underwent a low anterior resection and end-to-end anastomosis with loop ileostomy.\nPathology review of the resected rectosigmoid revealed a villous adenoma with low-grade dyplasia.\nThere was no evidence of muscularis propria invasion, and a total of five pericolic and two mesorectal lymph nodes were excised and deemed benign.\nThe patient underwent ileostomy reversal five months later.\nHe remains asymptomatic with no recurrence of tumours.",
    "action": "getDocument",
    "createdAt": {
        "$date": "2019-03-18T00:46:15.847Z"
    },
    "updatedAt": {
        "$date": "2019-03-18T00:46:15.847Z"
    },
    "__v": 0
}; export default docData;