const docData = {
    "_id": {
        "$oid": "5c8d8884402552326b063f66"
    },
    "messages": [],
    "source_files": [
        "ann",
        "txt"
    ],
    "modifications": [],
    "normalizations": [],
    "entities": [
        [
            "T1",
            "Age",
            [
                [
                    2,
                    13
                ]
            ]
        ],
        [
            "T2",
            "Gender",
            [
                [
                    14,
                    18
                ]
            ]
        ],
        [
            "T3",
            "Sign_symptom",
            [
                [
                    19,
                    31
                ]
            ]
        ],
        [
            "T4",
            "Ethnicity",
            [
                [
                    32,
                    41
                ]
            ]
        ],
        [
            "T5",
            "Therapeutic_procedure",
            [
                [
                    61,
                    78
                ]
            ]
        ],
        [
            "T7",
            "Disease_disorder",
            [
                [
                    98,
                    112
                ]
            ]
        ],
        [
            "T6",
            "Duration",
            [
                [
                    83,
                    93
                ]
            ]
        ],
        [
            "T8",
            "Activity",
            [
                [
                    117,
                    125
                ]
            ]
        ],
        [
            "T9",
            "Disease_disorder",
            [
                [
                    148,
                    176
                ]
            ]
        ],
        [
            "T10",
            "Quantitative_concept",
            [
                [
                    178,
                    192
                ]
            ]
        ],
        [
            "T11",
            "Sign_symptom",
            [
                [
                    199,
                    211
                ]
            ]
        ],
        [
            "T12",
            "Quantitative_concept",
            [
                [
                    260,
                    286
                ]
            ]
        ],
        [
            "T13",
            "Diagnostic_procedure",
            [
                [
                    307,
                    317
                ]
            ]
        ],
        [
            "T14",
            "Time",
            [
                [
                    346,
                    356
                ]
            ]
        ],
        [
            "T15",
            "Sign_symptom",
            [
                [
                    394,
                    414
                ]
            ]
        ],
        [
            "T16",
            "Quantitative_concept",
            [
                [
                    424,
                    435
                ]
            ]
        ],
        [
            "T17",
            "Sign_symptom",
            [
                [
                    416,
                    419
                ]
            ]
        ],
        [
            "T18",
            "Sign_symptom",
            [
                [
                    437,
                    473
                ]
            ]
        ],
        [
            "T19",
            "Sign_symptom",
            [
                [
                    475,
                    479
                ]
            ]
        ],
        [
            "T20",
            "Quantitative_concept",
            [
                [
                    484,
                    487
                ]
            ]
        ],
        [
            "T21",
            "Sign_symptom",
            [
                [
                    493,
                    512
                ]
            ]
        ],
        [
            "T22",
            "Sign_symptom",
            [
                [
                    514,
                    518
                ]
            ]
        ],
        [
            "T23",
            "Quantitative_concept",
            [
                [
                    522,
                    535
                ]
            ]
        ],
        [
            "T24",
            "Quantitative_concept",
            [
                [
                    540,
                    550
                ]
            ]
        ],
        [
            "T25",
            "Activity",
            [
                [
                    568,
                    578
                ]
            ]
        ],
        [
            "T26",
            "Therapeutic_procedure",
            [
                [
                    584,
                    601
                ]
            ]
        ],
        [
            "T27",
            "Therapeutic_procedure",
            [
                [
                    606,
                    631
                ]
            ]
        ],
        [
            "T28",
            "Diagnostic_procedure",
            [
                [
                    238,
                    240
                ]
            ]
        ],
        [
            "T29",
            "Age",
            [
                [
                    643,
                    654
                ]
            ]
        ],
        [
            "T30",
            "Gender",
            [
                [
                    663,
                    667
                ]
            ]
        ],
        [
            "T36",
            "Qualitative_concept",
            [
                [
                    748,
                    759
                ]
            ]
        ],
        [
            "T42",
            "Anatomical_structure",
            [
                [
                    921,
                    932
                ]
            ]
        ],
        [
            "T44",
            "Anatomical_structure",
            [
                [
                    993,
                    996
                ]
            ]
        ],
        [
            "T46",
            "Quantitative_concept",
            [
                [
                    1103,
                    1108
                ]
            ]
        ],
        [
            "T47",
            "Quantitative_concept",
            [
                [
                    1130,
                    1135
                ]
            ]
        ],
        [
            "T48",
            "Qualitative_concept",
            [
                [
                    1083,
                    1099
                ]
            ]
        ],
        [
            "T49",
            "Qualitative_concept",
            [
                [
                    1141,
                    1157
                ]
            ]
        ],
        [
            "T53",
            "Quantitative_concept",
            [
                [
                    1310,
                    1329
                ]
            ]
        ],
        [
            "T58",
            "Quantitative_concept",
            [
                [
                    1448,
                    1468
                ]
            ]
        ],
        [
            "T63",
            "Anatomical_structure",
            [
                [
                    1674,
                    1685
                ]
            ]
        ],
        [
            "T66",
            "Qualitative_concept",
            [
                [
                    1760,
                    1772
                ]
            ]
        ],
        [
            "T67",
            "Anatomical_structure",
            [
                [
                    1814,
                    1824
                ]
            ]
        ],
        [
            "T68",
            "Anatomical_structure",
            [
                [
                    1841,
                    1856
                ]
            ]
        ],
        [
            "T69",
            "Anatomical_structure",
            [
                [
                    1882,
                    1904
                ]
            ]
        ],
        [
            "T70",
            "Anatomical_structure",
            [
                [
                    1910,
                    1929
                ]
            ]
        ],
        [
            "T74",
            "Age",
            [
                [
                    2030,
                    2041
                ]
            ]
        ],
        [
            "T82",
            "Anatomical_structure",
            [
                [
                    2258,
                    2269
                ]
            ]
        ],
        [
            "T84",
            "Qualitative_concept",
            [
                [
                    2283,
                    2289
                ]
            ]
        ],
        [
            "T86",
            "Qualitative_concept",
            [
                [
                    2326,
                    2338
                ]
            ]
        ],
        [
            "T87",
            "Qualitative_concept",
            [
                [
                    2339,
                    2346
                ]
            ]
        ],
        [
            "T88",
            "Anatomical_structure",
            [
                [
                    2363,
                    2398
                ]
            ]
        ],
        [
            "T89",
            "Qualitative_concept",
            [
                [
                    2363,
                    2376
                ]
            ]
        ],
        [
            "T90",
            "Qualitative_concept",
            [
                [
                    2377,
                    2381
                ]
            ]
        ],
        [
            "T91",
            "Anatomical_structure",
            [
                [
                    2382,
                    2388
                ]
            ]
        ],
        [
            "T92",
            "Qualitative_concept",
            [
                [
                    2377,
                    2388
                ]
            ]
        ],
        [
            "T97",
            "Anatomical_structure",
            [
                [
                    2529,
                    2543
                ]
            ]
        ],
        [
            "T100",
            "Anatomical_structure",
            [
                [
                    2593,
                    2621
                ]
            ]
        ],
        [
            "T102",
            "Quantitative_concept",
            [
                [
                    2662,
                    2666
                ]
            ]
        ],
        [
            "T103",
            "Quantitative_concept",
            [
                [
                    2681,
                    2686
                ]
            ]
        ],
        [
            "T112",
            "Anatomical_structure",
            [
                [
                    2962,
                    2980
                ]
            ]
        ],
        [
            "T113",
            "Qualitative_concept",
            [
                [
                    2962,
                    2967
                ]
            ]
        ],
        [
            "T114",
            "Anatomical_structure",
            [
                [
                    3002,
                    3024
                ]
            ]
        ],
        [
            "T115",
            "Anatomical_structure",
            [
                [
                    3044,
                    3060
                ]
            ]
        ],
        [
            "T116",
            "Anatomical_structure",
            [
                [
                    3074,
                    3113
                ]
            ]
        ],
        [
            "T118",
            "Anatomical_structure",
            [
                [
                    3214,
                    3234
                ]
            ]
        ],
        [
            "T119",
            "Qualitative_concept",
            [
                [
                    3214,
                    3224
                ]
            ]
        ],
        [
            "T120",
            "Qualitative_concept",
            [
                [
                    3225,
                    3227
                ]
            ]
        ],
        [
            "T125",
            "Sex",
            [
                [
                    42,
                    49
                ]
            ]
        ]
    ],
    "attributes": [
        [
            "A1",
            "TREND",
            "E1",
            "DEC"
        ],
        [
            "A2",
            "TREND",
            "E14",
            "DEC"
        ],
        [
            "A3",
            "POLARITY",
            "E17",
            "NEG"
        ],
        [
            "A4",
            "POLARITY",
            "E20",
            "NEG"
        ],
        [
            "A5",
            "POLARITY",
            "E22",
            "MAYBE_POS"
        ],
        [
            "A6",
            "POLARITY",
            "E24",
            "NEG"
        ],
        [
            "A7",
            "POLARITY",
            "E45",
            "NEG"
        ],
        [
            "A8",
            "POLARITY",
            "E48",
            "NEG"
        ]
    ],
    "relations": [
        [
            "R1",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T10"
                ],
                [
                    "Arg2",
                    "T9"
                ]
            ]
        ],
        [
            "R2",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T20"
                ],
                [
                    "Arg2",
                    "T19"
                ]
            ]
        ],
        [
            "R3",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T20"
                ],
                [
                    "Arg2",
                    "T18"
                ]
            ]
        ],
        [
            "R4",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T23"
                ],
                [
                    "Arg2",
                    "T22"
                ]
            ]
        ],
        [
            "R5",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T24"
                ],
                [
                    "Arg2",
                    "T21"
                ]
            ]
        ],
        [
            "R6",
            "BEFORE",
            [
                [
                    "Arg1",
                    "T7"
                ],
                [
                    "Arg2",
                    "T8"
                ]
            ]
        ],
        [
            "R10",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T16"
                ],
                [
                    "Arg2",
                    "T17"
                ]
            ]
        ],
        [
            "R11",
            "BEFORE",
            [
                [
                    "Arg1",
                    "T22"
                ],
                [
                    "Arg2",
                    "T25"
                ]
            ]
        ],
        [
            "R7",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T36"
                ],
                [
                    "Arg2",
                    "E5"
                ]
            ]
        ],
        [
            "R12",
            "AFTER",
            [
                [
                    "Arg1",
                    "E2"
                ],
                [
                    "Arg2",
                    "E3"
                ]
            ]
        ],
        [
            "R13",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T42"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R14",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T44"
                ],
                [
                    "Arg2",
                    "E11"
                ]
            ]
        ],
        [
            "R15",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T48"
                ],
                [
                    "Arg2",
                    "T46"
                ]
            ]
        ],
        [
            "R16",
            "DECREASE_FROM",
            [
                [
                    "Arg1",
                    "E1"
                ],
                [
                    "Arg2",
                    "T46"
                ]
            ]
        ],
        [
            "R17",
            "DECREASE_TO",
            [
                [
                    "Arg1",
                    "E1"
                ],
                [
                    "Arg2",
                    "T47"
                ]
            ]
        ],
        [
            "R18",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T49"
                ],
                [
                    "Arg2",
                    "T47"
                ]
            ]
        ],
        [
            "R19",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E9"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R20",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T53"
                ],
                [
                    "Arg2",
                    "E15"
                ]
            ]
        ],
        [
            "R21",
            "AFTER",
            [
                [
                    "Arg1",
                    "E13"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R23",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T58"
                ],
                [
                    "Arg2",
                    "E19"
                ]
            ]
        ],
        [
            "R24",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T63"
                ],
                [
                    "Arg2",
                    "E23"
                ]
            ]
        ],
        [
            "R25",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E22"
                ],
                [
                    "Arg2",
                    "E23"
                ]
            ]
        ],
        [
            "R26",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T66"
                ],
                [
                    "Arg2",
                    "E25"
                ]
            ]
        ],
        [
            "R28",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T69"
                ],
                [
                    "Arg2",
                    "T68"
                ]
            ]
        ],
        [
            "R27",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T68"
                ],
                [
                    "Arg2",
                    "T67"
                ]
            ]
        ],
        [
            "R29",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T67"
                ],
                [
                    "Arg2",
                    "E25"
                ]
            ]
        ],
        [
            "R30",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T70"
                ],
                [
                    "Arg2",
                    "E28"
                ]
            ]
        ],
        [
            "R31",
            "AFTER",
            [
                [
                    "Arg1",
                    "E29"
                ],
                [
                    "Arg2",
                    "E30"
                ]
            ]
        ],
        [
            "R32",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E2"
                ],
                [
                    "Arg2",
                    "E10"
                ]
            ]
        ],
        [
            "R34",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T82"
                ],
                [
                    "Arg2",
                    "E35"
                ]
            ]
        ],
        [
            "R35",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T84"
                ],
                [
                    "Arg2",
                    "E36"
                ]
            ]
        ],
        [
            "R36",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E31"
                ],
                [
                    "Arg2",
                    "E33"
                ]
            ]
        ],
        [
            "R38",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E34"
                ],
                [
                    "Arg2",
                    "E35"
                ]
            ]
        ],
        [
            "R37",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T86"
                ],
                [
                    "Arg2",
                    "E37"
                ]
            ]
        ],
        [
            "R39",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T87"
                ],
                [
                    "Arg2",
                    "E37"
                ]
            ]
        ],
        [
            "R40",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T90"
                ],
                [
                    "Arg2",
                    "T91"
                ]
            ]
        ],
        [
            "R41",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T92"
                ],
                [
                    "Arg2",
                    "T88"
                ]
            ]
        ],
        [
            "R42",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T89"
                ],
                [
                    "Arg2",
                    "T88"
                ]
            ]
        ],
        [
            "R43",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T88"
                ],
                [
                    "Arg2",
                    "E37"
                ]
            ]
        ],
        [
            "R44",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E36"
                ],
                [
                    "Arg2",
                    "E37"
                ]
            ]
        ],
        [
            "R45",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T100"
                ],
                [
                    "Arg2",
                    "E43"
                ]
            ]
        ],
        [
            "R46",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T97"
                ],
                [
                    "Arg2",
                    "E41"
                ]
            ]
        ],
        [
            "R47",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E40"
                ],
                [
                    "Arg2",
                    "E41"
                ]
            ]
        ],
        [
            "R48",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T102"
                ],
                [
                    "Arg2",
                    "E44"
                ]
            ]
        ],
        [
            "R49",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T103"
                ],
                [
                    "Arg2",
                    "E44"
                ]
            ]
        ],
        [
            "R50",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E44"
                ],
                [
                    "Arg2",
                    "E45"
                ]
            ]
        ],
        [
            "R51",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E45"
                ],
                [
                    "Arg2",
                    "E46"
                ]
            ]
        ],
        [
            "R52",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E47"
                ],
                [
                    "Arg2",
                    "E49"
                ]
            ]
        ],
        [
            "R55",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E51"
                ],
                [
                    "Arg2",
                    "E52"
                ]
            ]
        ],
        [
            "R53",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E31"
                ],
                [
                    "Arg2",
                    "E51"
                ]
            ]
        ],
        [
            "R54",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T113"
                ],
                [
                    "Arg2",
                    "T112"
                ]
            ]
        ],
        [
            "R57",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T114"
                ],
                [
                    "Arg2",
                    "T112"
                ]
            ]
        ],
        [
            "R58",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T116"
                ],
                [
                    "Arg2",
                    "T112"
                ]
            ]
        ],
        [
            "R59",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T119"
                ],
                [
                    "Arg2",
                    "T118"
                ]
            ]
        ],
        [
            "R60",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T120"
                ],
                [
                    "Arg2",
                    "T118"
                ]
            ]
        ],
        [
            "R61",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T118"
                ],
                [
                    "Arg2",
                    "E53"
                ]
            ]
        ],
        [
            "R63",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T115"
                ],
                [
                    "Arg2",
                    "T112"
                ]
            ]
        ],
        [
            "R64",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T91"
                ],
                [
                    "Arg2",
                    "T88"
                ]
            ]
        ],
        [
            "R66",
            "AFTER",
            [
                [
                    "Arg1",
                    "E48"
                ],
                [
                    "Arg2",
                    "E49"
                ]
            ]
        ],
        [
            "R67",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T12"
                ],
                [
                    "Arg2",
                    "T28"
                ]
            ]
        ],
        [
            "R8",
            "BEFORE",
            [
                [
                    "Arg1",
                    "T28"
                ],
                [
                    "Arg2",
                    "E54"
                ]
            ]
        ],
        [
            "R68",
            "AFTER",
            [
                [
                    "Arg1",
                    "T14"
                ],
                [
                    "Arg2",
                    "E54"
                ]
            ]
        ],
        [
            "R69",
            "BEFORE",
            [
                [
                    "Arg1",
                    "T8"
                ],
                [
                    "Arg2",
                    "T11"
                ]
            ]
        ],
        [
            "R9",
            "BEFORE",
            [
                [
                    "Arg1",
                    "T13"
                ],
                [
                    "Arg2",
                    "T15"
                ]
            ]
        ],
        [
            "R70",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E10"
                ],
                [
                    "Arg2",
                    "E11"
                ]
            ]
        ],
        [
            "R71",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E11"
                ],
                [
                    "Arg2",
                    "E12"
                ]
            ]
        ],
        [
            "R72",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E12"
                ],
                [
                    "Arg2",
                    "E1"
                ]
            ]
        ],
        [
            "R74",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E23"
                ],
                [
                    "Arg2",
                    "E24"
                ]
            ]
        ],
        [
            "R75",
            "AFTER",
            [
                [
                    "Arg1",
                    "E14"
                ],
                [
                    "Arg2",
                    "E55"
                ]
            ]
        ],
        [
            "R22",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E1"
                ],
                [
                    "Arg2",
                    "E55"
                ]
            ]
        ],
        [
            "R73",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E1"
                ],
                [
                    "Arg2",
                    "E16"
                ]
            ]
        ],
        [
            "R76",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E35"
                ],
                [
                    "Arg2",
                    "E36"
                ]
            ]
        ],
        [
            "R77",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E37"
                ],
                [
                    "Arg2",
                    "E38"
                ]
            ]
        ],
        [
            "R78",
            "AFTER",
            [
                [
                    "Arg1",
                    "E56"
                ],
                [
                    "Arg2",
                    "E52"
                ]
            ]
        ],
        [
            "R62",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "T112"
                ],
                [
                    "Arg2",
                    "E56"
                ]
            ]
        ],
        [
            "R79",
            "BEFORE",
            [
                [
                    "Arg1",
                    "E56"
                ],
                [
                    "Arg2",
                    "E53"
                ]
            ]
        ],
        [
            "R33",
            "MODIFIER",
            [
                [
                    "Arg1",
                    "E57"
                ],
                [
                    "Arg2",
                    "E32"
                ]
            ]
        ]
    ],
    "triggers": [
        [
            "T31",
            "Sign_symptom",
            [
                [
                    1067,
                    1077
                ]
            ]
        ],
        [
            "T32",
            "Activity",
            [
                [
                    668,
                    677
                ]
            ]
        ],
        [
            "T33",
            "Activity",
            [
                [
                    712,
                    734
                ]
            ]
        ],
        [
            "T34",
            "Activity",
            [
                [
                    741,
                    759
                ]
            ]
        ],
        [
            "T35",
            "Activity",
            [
                [
                    741,
                    747
                ]
            ]
        ],
        [
            "T37",
            "Activity",
            [
                [
                    777,
                    793
                ]
            ]
        ],
        [
            "T38",
            "Disease_disorder",
            [
                [
                    808,
                    830
                ]
            ]
        ],
        [
            "T39",
            "Disease_disorder",
            [
                [
                    837,
                    873
                ]
            ]
        ],
        [
            "T40",
            "Disease_disorder",
            [
                [
                    882,
                    904
                ]
            ]
        ],
        [
            "T41",
            "Diagnostic_procedure",
            [
                [
                    906,
                    941
                ]
            ]
        ],
        [
            "T43",
            "Sign_symptom",
            [
                [
                    951,
                    996
                ]
            ]
        ],
        [
            "T45",
            "Diagnostic_procedure",
            [
                [
                    1004,
                    1030
                ]
            ]
        ],
        [
            "T50",
            "Disease_disorder",
            [
                [
                    1163,
                    1174
                ]
            ]
        ],
        [
            "T51",
            "Disease_disorder",
            [
                [
                    1246,
                    1257
                ]
            ]
        ],
        [
            "T52",
            "Sign_symptom",
            [
                [
                    1283,
                    1299
                ]
            ]
        ],
        [
            "T54",
            "Sign_symptom",
            [
                [
                    1204,
                    1226
                ]
            ]
        ],
        [
            "T55",
            "Sign_symptom",
            [
                [
                    1390,
                    1407
                ]
            ]
        ],
        [
            "T56",
            "Disease_disorder",
            [
                [
                    1419,
                    1430
                ]
            ]
        ],
        [
            "T57",
            "Disease_disorder",
            [
                [
                    1472,
                    1480
                ]
            ]
        ],
        [
            "T59",
            "Diagnostic_procedure",
            [
                [
                    1517,
                    1541
                ]
            ]
        ],
        [
            "T60",
            "Disease_disorder",
            [
                [
                    1591,
                    1602
                ]
            ]
        ],
        [
            "T61",
            "Disease_disorder",
            [
                [
                    1618,
                    1651
                ]
            ]
        ],
        [
            "T62",
            "Diagnostic_procedure",
            [
                [
                    1664,
                    1685
                ]
            ]
        ],
        [
            "T64",
            "Disease_disorder",
            [
                [
                    1702,
                    1733
                ]
            ]
        ],
        [
            "T65",
            "Sign_symptom",
            [
                [
                    1776,
                    1787
                ]
            ]
        ],
        [
            "T71",
            "Disease_disorder",
            [
                [
                    1966,
                    1981
                ]
            ]
        ],
        [
            "T72",
            "Disease_disorder",
            [
                [
                    2001,
                    2018
                ]
            ]
        ],
        [
            "T73",
            "Disease_disorder",
            [
                [
                    1910,
                    1953
                ]
            ]
        ],
        [
            "T75",
            "Disease_disorder",
            [
                [
                    2054,
                    2096
                ]
            ]
        ],
        [
            "T76",
            "Therapeutic_procedure",
            [
                [
                    2111,
                    2153
                ]
            ]
        ],
        [
            "T77",
            "Activity",
            [
                [
                    2158,
                    2166
                ]
            ]
        ],
        [
            "T79",
            "Therapeutic_procedure",
            [
                [
                    2200,
                    2208
                ]
            ]
        ],
        [
            "T80",
            "Sign_symptom",
            [
                [
                    2210,
                    2229
                ]
            ]
        ],
        [
            "T81",
            "Diagnostic_procedure",
            [
                [
                    2243,
                    2250
                ]
            ]
        ],
        [
            "T83",
            "Sign_symptom",
            [
                [
                    2290,
                    2314
                ]
            ]
        ],
        [
            "T85",
            "Diagnostic_procedure",
            [
                [
                    2326,
                    2359
                ]
            ]
        ],
        [
            "T93",
            "Sign_symptom",
            [
                [
                    2412,
                    2433
                ]
            ]
        ],
        [
            "T94",
            "Sign_symptom",
            [
                [
                    2439,
                    2458
                ]
            ]
        ],
        [
            "T95",
            "Sign_symptom",
            [
                [
                    2475,
                    2499
                ]
            ]
        ],
        [
            "T96",
            "Therapeutic_procedure",
            [
                [
                    2508,
                    2523
                ]
            ]
        ],
        [
            "T98",
            "Diagnostic_procedure",
            [
                [
                    2550,
                    2575
                ]
            ]
        ],
        [
            "T99",
            "Disease_disorder",
            [
                [
                    2583,
                    2587
                ]
            ]
        ],
        [
            "T101",
            "Therapeutic_procedure",
            [
                [
                    2631,
                    2653
                ]
            ]
        ],
        [
            "T104",
            "Disease_disorder",
            [
                [
                    2689,
                    2703
                ]
            ]
        ],
        [
            "T105",
            "Disease_disorder",
            [
                [
                    2738,
                    2761
                ]
            ]
        ],
        [
            "T106",
            "Therapeutic_procedure",
            [
                [
                    2772,
                    2795
                ]
            ]
        ],
        [
            "T107",
            "Sign_symptom",
            [
                [
                    2810,
                    2833
                ]
            ]
        ],
        [
            "T108",
            "Duration",
            [
                [
                    2840,
                    2846
                ]
            ]
        ],
        [
            "T109",
            "Therapeutic_procedure",
            [
                [
                    2854,
                    2873
                ]
            ]
        ],
        [
            "T110",
            "Diagnostic_procedure",
            [
                [
                    2901,
                    2933
                ]
            ]
        ],
        [
            "T111",
            "Therapeutic_procedure",
            [
                [
                    2941,
                    2950
                ]
            ]
        ],
        [
            "T117",
            "Diagnostic_procedure",
            [
                [
                    3156,
                    3190
                ]
            ]
        ],
        [
            "T121",
            "Diagnostic_procedure",
            [
                [
                    367,
                    376
                ]
            ]
        ],
        [
            "T122",
            "Duration",
            [
                [
                    1336,
                    1360
                ]
            ]
        ],
        [
            "T123",
            "Activity",
            [
                [
                    2891,
                    2897
                ]
            ]
        ],
        [
            "T78",
            "Date",
            [
                [
                    2097,
                    2110
                ]
            ]
        ],
        [
            "T124",
            "Duration",
            [
                [
                    2097,
                    2104
                ]
            ]
        ]
    ],
    "events": [
        [
            "E1",
            "T31",
            []
        ],
        [
            "E2",
            "T32",
            []
        ],
        [
            "E3",
            "T33",
            []
        ],
        [
            "E4",
            "T34",
            []
        ],
        [
            "E5",
            "T35",
            []
        ],
        [
            "E6",
            "T37",
            []
        ],
        [
            "E7",
            "T38",
            []
        ],
        [
            "E8",
            "T39",
            []
        ],
        [
            "E9",
            "T40",
            []
        ],
        [
            "E10",
            "T41",
            []
        ],
        [
            "E11",
            "T43",
            []
        ],
        [
            "E12",
            "T45",
            []
        ],
        [
            "E13",
            "T50",
            []
        ],
        [
            "E14",
            "T51",
            []
        ],
        [
            "E15",
            "T52",
            []
        ],
        [
            "E16",
            "T54",
            []
        ],
        [
            "E17",
            "T55",
            []
        ],
        [
            "E18",
            "T56",
            []
        ],
        [
            "E19",
            "T57",
            []
        ],
        [
            "E20",
            "T59",
            []
        ],
        [
            "E21",
            "T60",
            []
        ],
        [
            "E22",
            "T61",
            []
        ],
        [
            "E23",
            "T62",
            []
        ],
        [
            "E24",
            "T64",
            []
        ],
        [
            "E25",
            "T65",
            []
        ],
        [
            "E26",
            "T71",
            []
        ],
        [
            "E27",
            "T72",
            []
        ],
        [
            "E28",
            "T73",
            []
        ],
        [
            "E29",
            "T75",
            []
        ],
        [
            "E30",
            "T76",
            []
        ],
        [
            "E31",
            "T77",
            []
        ],
        [
            "E33",
            "T79",
            []
        ],
        [
            "E34",
            "T80",
            []
        ],
        [
            "E35",
            "T81",
            []
        ],
        [
            "E36",
            "T83",
            []
        ],
        [
            "E37",
            "T85",
            []
        ],
        [
            "E38",
            "T93",
            []
        ],
        [
            "E39",
            "T94",
            []
        ],
        [
            "E40",
            "T95",
            []
        ],
        [
            "E41",
            "T96",
            []
        ],
        [
            "E42",
            "T98",
            []
        ],
        [
            "E43",
            "T99",
            []
        ],
        [
            "E44",
            "T101",
            []
        ],
        [
            "E45",
            "T104",
            []
        ],
        [
            "E46",
            "T105",
            []
        ],
        [
            "E47",
            "T106",
            []
        ],
        [
            "E48",
            "T107",
            []
        ],
        [
            "E49",
            "T108",
            []
        ],
        [
            "E50",
            "T109",
            []
        ],
        [
            "E51",
            "T110",
            []
        ],
        [
            "E52",
            "T111",
            []
        ],
        [
            "E53",
            "T117",
            []
        ],
        [
            "E54",
            "T121",
            []
        ],
        [
            "E55",
            "T122",
            []
        ],
        [
            "E56",
            "T123",
            []
        ],
        [
            "E32",
            "T78",
            []
        ],
        [
            "E57",
            "T124",
            []
        ]
    ],
    "equivs": [
        [
            "*",
            "OVERLAP",
            "T6",
            "T5",
            "T7",
            "T3"
        ],
        [
            "*",
            "OVERLAP",
            "T8",
            "T9"
        ],
        [
            "*",
            "OVERLAP",
            "T25",
            "T26",
            "T27"
        ],
        [
            "*",
            "OVERLAP",
            "E9",
            "E8",
            "E7",
            "E6",
            "E4",
            "E3",
            "E5"
        ],
        [
            "*",
            "OVERLAP",
            "E21",
            "E22",
            "E18",
            "E19",
            "E20",
            "E17",
            "E1"
        ],
        [
            "*",
            "OVERLAP",
            "E28",
            "E26",
            "E27",
            "E25",
            "E24"
        ],
        [
            "*",
            "OVERLAP",
            "E33",
            "E34",
            "E52"
        ],
        [
            "*",
            "OVERLAP",
            "E39",
            "E40",
            "E38"
        ],
        [
            "*",
            "OVERLAP",
            "E41",
            "E42",
            "E43",
            "E44"
        ],
        [
            "*",
            "OVERLAP",
            "E46",
            "E47"
        ],
        [
            "*",
            "OVERLAP",
            "E48",
            "E50"
        ],
        [
            "*",
            "OVERLAP",
            "T11",
            "T28"
        ],
        [
            "*",
            "OVERLAP",
            "T13",
            "T14"
        ],
        [
            "*",
            "OVERLAP",
            "T15",
            "T17",
            "T18",
            "T19",
            "T21",
            "T22"
        ],
        [
            "*",
            "OVERLAP",
            "E14",
            "E15"
        ],
        [
            "*",
            "OVERLAP",
            "E29",
            "E32",
            "E31"
        ]
    ],
    "comments": [
        [
            "T28",
            "AnnotatorNotes",
            "?"
        ],
        [
            "E42",
            "AnnotatorNotes",
            "apple"
        ]
    ],
    "text": "A 57-year-old male hypertensive Caucasian patient who was on medical treatment for 1.5 months for non-organic AF was admitted to the ICU because of high-ventricular response AF (170 per minute), and sinus rhythm was maintained during the CV that was performed two times every second day. The results of the apnea test performed in the ICU on the same night after the second CV were as follows: apnea-hypopnea index (AHI) of 71 per hour, minimum peripheral oxygen saturation (SpO2) of 67%, and desaturation period (SpO2 of less than 90%) of 28 minutes. The patient was discharged with medical treatment and nocturnal BiPAP treatment. \nCase 2\nA 33-year-old healthy male presented to the emergency department after falling from a bicycle while riding intoxicated. The patient was wearing a helmet but sustained unilateral lacerations and a zygomaticomaxillary complex fracture with an orbital floor fracture. Examination of extraocular motility revealed a-2 restriction in upgaze in the affected eye, and a continuous cardiac monitor revealed a reproducible decrease in heart rate from a baseline pulse of 65\u201370 to a pulse as low as 42\u201345 with attempted upgaze. The bradycardia would promptly resolve after return to primary gaze, and the degree of bradycardia would also diminish with sustained upgaze to around 50 beats per minute after approximately 20 seconds. The patient did not endorse syncopal symptoms during the bradycardia, but he did have 3 witnessed episodes of vomiting, while in the emergency department. The rest of the eye exam was unremarkable. It was felt initially that the bradycardia was related to inferior rectus muscle entrapment. However, a CT of the head/orbits demonstrated no prolapse of the inferior rectus but instead evidence of a small amount of soft tissue, which likely represented adventitia surrounding the inferior rectus trapped in and below the orbital floor fracture. The orbital floor bones were also non-displaced with only a linear fracture, consistent with a trapdoor fracture. \nCase 3\nA 74-year-old man who had drug-refractory paroxys-mal atrial flutter 2 years after circumferential pulmonary venous isolation was referred to our hospital. During repeated ablation, clinical arrhythmia was induced. Mapping of the left atrium revealed the entire tachycardia cycle length. Capturing fractionated bipolar electrograms at anterolateral left atrial (LA) wall demonstrated concealed entrainment with postpacing interval comparable with tachycardia cycle length. During linear ablation from mitral annulus along fractionated electrograms to the scar near left superior pulmonary vein using an irrigated tip catheter (power, 35 W; temperature, 40 oC), atrial flutter terminated, which was followed by sinus nodal (SN) arrest requiring urgent temporary pacing. There was no recovery of SN function after 3 days, and a permanent pacemaker was implanted. A review of cardiac computed tomography (CT) before abla-tion revealed a small blood vessel originating from the left circumflex artery, running along the anterior LA wall to reach the cavoatrial junction of the right atrium, which was not seen in postablation CT. A 3-dimensional reconstruction image showed that this was a left-sided SN artery. \nCase 4\nA 58-year-old patient with a 3-year history of paroxysmal atrial fibrillation underwent circumferential pulmonary vein isolation (PVI) in 2012. After 3 months, he presented with a symptomatic LAMRT with a cycle length of 385 ms (. Fig. 1). The patient was on amiodarone (200 mg daily). A PVI-redo was performed using a novel circular mapping and abla-tion catheter (nMarq, Biosense Webster, Diamond Bar, Calif., USA). This is a ten-electrode steerable lasso-shaped cathe-ter that allows irrigated unipolar and bi-polar radiofrequency (RF) ablation (cool flow of 60 ml/min). Each electrode can be switched on and off separately. For PVI, an antral ablation (outside the PV) was performed. After single transseptal puncture , a CARTO 3 map of the left atrium was acquired using the nMarq catheter. The activation map revealed an LAMRT with its exit to the left atrium (LA) at the roof of the left superior pulmonary vein (LSPV) and its entrance at the bottom of the left inferior pulmonary vein (LIPV;. Fig. 2) By placing the nMarq catheter at the ostium of the LSPV, the activation sequence could be nicely depicted. Pacing from the roof of the LSPV showed perfect entrainment (PPI  8 ms) and a similar p-wave morphology compared to the tachy-cardia. Ablation at this site terminated the LAMRT. The exit to the LA was blocked. Conduction into the left pulmonary veins was still present because of the gap at the bottom of the LIPV (. Fig. 3). After ab-lation at this site, the lateral pulmonary veins were isolated. The septal ablation line showed gaps in the anteriorinferior part, which were successfully closed. At the end of the procedure there was no in-ducible tachycardia. The septal and lateral PVs were isolated. The patient was free of any tachycardia for 6 months. Conclusion The reentrant circuit of this LAMRT could be nicely depicted using the nMarq catheter. Successful ablation at the exit and entrance site could be performed without moving the catheter.\nCase 5\nA 39-year-old obese woman presented with influenza A (H1N1)-related acute respiratory distress syndrome (ARDS). At day 2, refractory hypoxemia ensued and veno-venous extracorporeal membrane oxygenation (ECMO) was initiated. At day 15, venous catheter-related infection was suspected and a left subclavian venous catheter was inserted using the Seldinger technique, with blood that was freely aspirated before and after insertion of the catheter. However, acute circulatory shock was observed shortly afterwards. The transthoracic echocardiogram revealed pericardial effusion with collapsed right chambers, suggesting cardiac tamponade. The chest X-ray (Fig. 1) showed a malposi-tioned catheter in the left lung. Cardiac arrest ensued and emergent sternotomy was performed under ECMO-assisted cardiopulmonary resuscitation after femoral artery cannu-lation (venous-venous-arterial ECMO). Pulmonary artery perforation (Fig. 2) and hemopericardium were then surgically repaired after catheter withdrawal. Her hospital course was further complicated by severe ARDS secondary to Enterococcus faecalis bacteremia with redo veno-venous ECMO. The patient made a full recovery and was discharged home 2.5 months after hospital admission with no neuro-logic or cardiopulmonary sequelae. Fig. 1 Chest X-ray showing the malpositioned left subclavian central venous catheter Intensive .\nCase 6\nA 54-year-old woman presented with giant struma, hyperthyroidism of unknown duration, palpitations and dyspnoea. The ECG showed tachycardia atrial fibrillation. Echocardiography revealed dilatation of the left ventricle, highly reduced systolic function and diffuse hypokinesia. Serum thyroid stimulating hormone (TSH) levels were less than 0.03 lU/ml (physiological range 0.554.78 lU/ ml), free triiodothyronine (fT3) was 7.32 pg/ml (2.304.20 pg/ml) and free thyroxine (fT4) amounted to Fig. 1 Turbo field-echo (TFE) inversion recovery (IR) sequences in vertical (a) and horizontal (b) long axis 10 min after intravenous gadolinium-based contrast agent administration: the healthy basal and midventricular myocardium shows no prolonged gadolinium retention and is depicted in black (arrowheads), whereas the transmural scar in the apical segments retains the gadolinium and has a bright appearance (arrows). \nCase 7\nIn the last decades, number of drugs were withdrawn due to cases of TdP, leading to intensify assessment of drug QT interval. In our case, hydroxyzine was identified as the only drug able to induce QTc interval prolongation in the patients active medication. Moreover, a hydroxyzine overdose was detected probably due to high posology, bile ducts obstruction, and liver impairment (rise in GPT). Cetirizine is the hydroxyzines major active metabolite; unfortunately, its blood level dosage was not performed. We suppose that combination of hydroxyzine overdose and transient renal failure could have lead to cetirizine accumulation. However, cetirizine seems to be safe regarding ventricular repolarization, even at supratherapeutic dose. Theres only one published clinical case of hydroxyzine-induced QT prolongation. This case describes recurrent syncope during hydroxyzine treatment at usual posology in a 34-year-old woman presenting a hERG mutation. hERG gene codes for the subunit of a potassium channel (I Kr ) implicated in the ventricular repolarization. Experimentally, it was shown that hydroxyzine could be proarrhythmic by blocking hERG channels and therefore prolonging action potential duration, thus inducing TdP. In the French pharmacovigilance database, we found 24 cases of QT prolongation mentioning hydroxyzine with a suspected accountability assumed in 7 cases. We publish here the first clinical case of hydroxyzineassociated QT prolongation with drug dosage data. The association of hydroxyzine, especially at high posology, and others already well-known TdP risks factors (including hypokalemia and bradycardia) could induce QT prolongation and lifethreatening TdP. The present work underlines the recent addition of hydroxyzine to the list of drugs with conditional risk of TdP and drugs to be avoided by patients with congenital long QT syndrome. It also reminds that recommended hydroxyzines posology must be respected, the risk of QT prolongation and syncope increases dramatically in case of an overdose. Finally, considering the large use of the molecule, the recurrence of hydroxyzine-induced QT prolongation is probably underestimated. ",
    "action": "getDocument",
    "createdAt": {
        "$date": "2019-03-16T23:36:37.009Z"
    },
    "updatedAt": {
        "$date": "2019-03-16T23:36:37.009Z"
    },
    "__v": 0
}; export default docData;